<?php

declare(strict_types=1);

/**
 * This file is part of Narrowspark Framework.
 *
 * (c) Daniel Bannert <d.bannert@anolilab.de>
 *
 * This source file is subject to the MIT license that is bundled
 * with this source code in the file LICENSE.
 */

namespace Viserio\Component\Translation\Tests\Container\Provider\Compiled;

/**
 * This class has been auto-generated by Viserio Container Component.
 */
if (\class_exists(\ContainerC840be5a626a0086c4031c25a32260d1b415406652cbcc4e146b99bc52929bf9\TranslatorServiceProviderContainer::class, false)) {
    // no-op
} elseif (! include __DIR__ . '/ContainerC840be5a626a0086c4031c25a32260d1b415406652cbcc4e146b99bc52929bf9/TranslatorServiceProviderContainer.php') {
    \touch(__DIR__ . '/ContainerC840be5a626a0086c4031c25a32260d1b415406652cbcc4e146b99bc52929bf9.legacy');

    return;
}

if (! \class_exists(TranslatorServiceProviderContainer::class, false)) {
    \class_alias(\ContainerC840be5a626a0086c4031c25a32260d1b415406652cbcc4e146b99bc52929bf9\TranslatorServiceProviderContainer::class, TranslatorServiceProviderContainer::class, false);
}

return new \ContainerC840be5a626a0086c4031c25a32260d1b415406652cbcc4e146b99bc52929bf9\TranslatorServiceProviderContainer([
    'container.build_hash' => 'C840be5a626a0086c4031c25a32260d1b415406652cbcc4e146b99bc52929bf9',
    'container.build_id' => '7da35e90',
    'container.build_time' => 1565458035,
], __DIR__ . '/ContainerC840be5a626a0086c4031c25a32260d1b415406652cbcc4e146b99bc52929bf9');
