<?php

declare(strict_types=1);

/**
 * This file is part of Narrowspark Framework.
 *
 * (c) Daniel Bannert <d.bannert@anolilab.de>
 *
 * This source file is subject to the MIT license that is bundled
 * with this source code in the file LICENSE.
 */

namespace Viserio\Component\Routing\Tests\Provider\Compiled;

/**
 * This class has been auto-generated by Viserio Container Component.
 */
final class ConsoleCommandsServiceProviderContainer extends \Viserio\Component\Container\AbstractCompiledContainer
{
    /**
     * Create a new Compiled Container instance.
     */
    public function __construct()
    {
        $this->services = $this->privates = [];
        $this->methodMapping = [
            \Symfony\Component\Console\CommandLoader\CommandLoaderInterface::class => 'getce817e8bdc75399a693ba45b876c457a0f7fd422258f7d4eabc553987c2fbd31',
            \Viserio\Component\Console\Application::class => 'get206058a713a7172158e11c9d996f6a067c294ab0356ae6697060f162e057445a',
            \Viserio\Contract\Routing\Dispatcher::class => 'getdbf0d80bb72faf68b0e64ae28f321f2937bbd0a5641dc6e0e3c14d77ac90cebc',
            \Viserio\Contract\Routing\Router::class => 'get639eadb41acec5a4682e33d3d5a4fac1a0988b27ef4f45751735b2950eb42b56',
            \Viserio\Component\Routing\Command\RouteListCommand::class => 'get5f34d750a5fcad2449cb7b81f89a57492dc2a795006c02d9b865276ad3291746',
            'config' => 'get34bcaa5afa8745d92e6161e8495be3b939c5c6abb4dc2fd1f5a3cfdaba620256',
            'console.command.ids' => 'getdbce155f9c0e95dbd4bfbfaadab27eb79915789fa80c6c65068ccf60c9ef9e18',
        ];
        $this->aliases = [
            \Symfony\Component\Console\Application::class => \Viserio\Component\Console\Application::class,
            \Viserio\Component\Routing\Router::class => \Viserio\Contract\Routing\Router::class,
            'cerebro' => \Viserio\Component\Console\Application::class,
            'console' => \Viserio\Component\Console\Application::class,
            'route' => \Viserio\Contract\Routing\Router::class,
            'router' => \Viserio\Contract\Routing\Router::class,
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function getRemovedIds(): array
    {
        return [
            \Psr\Container\ContainerInterface::class => true,
            \Viserio\Contract\Container\Factory::class => true,
            \Viserio\Contract\Container\TaggedContainer::class => true,
            'container' => true,
        ];
    }

    /**
     * Returns the public Symfony\Component\Console\CommandLoader\CommandLoaderInterface shared service.
     *
     * @return \Viserio\Component\Console\CommandLoader\IteratorCommandLoader
     */
    protected function getce817e8bdc75399a693ba45b876c457a0f7fd422258f7d4eabc553987c2fbd31(): \Viserio\Component\Console\CommandLoader\IteratorCommandLoader
    {
        return $this->services[\Symfony\Component\Console\CommandLoader\CommandLoaderInterface::class] = new \Viserio\Component\Console\CommandLoader\IteratorCommandLoader(new \Viserio\Component\Container\RewindableGenerator(function () {
            yield 'route:table' => ($this->services[\Viserio\Component\Routing\Command\RouteListCommand::class] ?? $this->get5f34d750a5fcad2449cb7b81f89a57492dc2a795006c02d9b865276ad3291746());
        }, 1));
    }

    /**
     * Returns the public Viserio\Component\Console\Application shared service.
     *
     * @return \Viserio\Component\Console\Application
     */
    protected function get206058a713a7172158e11c9d996f6a067c294ab0356ae6697060f162e057445a(): \Viserio\Component\Console\Application
    {
        $this->services[\Viserio\Component\Console\Application::class] = $instance = new \Viserio\Component\Console\Application();

        $instance->setContainer($this);

        if ($this->has(\Symfony\Component\Console\CommandLoader\CommandLoaderInterface::class)) {
            $instance->setCommandLoader(($this->services[\Symfony\Component\Console\CommandLoader\CommandLoaderInterface::class] ?? $this->getce817e8bdc75399a693ba45b876c457a0f7fd422258f7d4eabc553987c2fbd31()));
        }

        return $instance;
    }

    /**
     * Returns the public Viserio\Contract\Routing\Dispatcher shared service.
     *
     * @return \Viserio\Component\Routing\Dispatcher\MiddlewareBasedDispatcher
     */
    protected function getdbf0d80bb72faf68b0e64ae28f321f2937bbd0a5641dc6e0e3c14d77ac90cebc(): \Viserio\Component\Routing\Dispatcher\MiddlewareBasedDispatcher
    {
        return $this->services[\Viserio\Contract\Routing\Dispatcher::class] = new \Viserio\Component\Routing\Dispatcher\MiddlewareBasedDispatcher();
    }

    /**
     * Returns the public Viserio\Contract\Routing\Router shared service.
     *
     * @return \Viserio\Component\Routing\Router
     */
    protected function get639eadb41acec5a4682e33d3d5a4fac1a0988b27ef4f45751735b2950eb42b56(): \Viserio\Component\Routing\Router
    {
        $this->services[\Viserio\Contract\Routing\Router::class] = $instance = new \Viserio\Component\Routing\Router(($this->services[\Viserio\Contract\Routing\Dispatcher::class] ?? $this->getdbf0d80bb72faf68b0e64ae28f321f2937bbd0a5641dc6e0e3c14d77ac90cebc()));

        $instance->setContainer($this);

        return $instance;
    }

    /**
     * Returns the public Viserio\Component\Routing\Command\RouteListCommand shared service.
     *
     * @return \Viserio\Component\Routing\Command\RouteListCommand
     */
    protected function get5f34d750a5fcad2449cb7b81f89a57492dc2a795006c02d9b865276ad3291746(): \Viserio\Component\Routing\Command\RouteListCommand
    {
        $this->services[\Viserio\Component\Routing\Command\RouteListCommand::class] = $instance = new \Viserio\Component\Routing\Command\RouteListCommand(($this->services[\Viserio\Contract\Routing\Router::class] ?? $this->get639eadb41acec5a4682e33d3d5a4fac1a0988b27ef4f45751735b2950eb42b56()));

        $instance->setName('route:table');

        return $instance;
    }

    /**
     * Returns the public config service.
     *
     * @return array
     */
    protected function get34bcaa5afa8745d92e6161e8495be3b939c5c6abb4dc2fd1f5a3cfdaba620256(): array
    {
        return [
            'viserio' => [
                'routing' => [
                    'path' => '',
                ],
            ],
        ];
    }

    /**
     * Returns the public console.command.ids service.
     *
     * @return array
     */
    protected function getdbce155f9c0e95dbd4bfbfaadab27eb79915789fa80c6c65068ccf60c9ef9e18(): array
    {
        return [];
    }
}
