<?php

declare(strict_types=1);

namespace Viserio\Component\Routing\Tests\Provider\Compiled;

/**
 * This class has been auto-generated by Viserio Container Component.
 */
final class ConsoleCommandsServiceProviderContainer extends \Viserio\Component\Container\AbstractCompiledContainer
{
    /**
     * Create a new Compiled Container instance.
     */
    public function __construct()
    {
        $this->services = $this->privates = [];
        $this->parameters = [
            'viserio' => [
                'console' => [
                    'name' => 'test',
                    'version' => '1',
                ],
            ],
            'console.command.ids' => [],
        ];
        $this->methodMapping = [
            \Symfony\Component\Console\CommandLoader\CommandLoaderInterface::class => 'getce817e8bdc75399a693ba45b876c457a0f7fd422258f7d4eabc553987c2fbd31',
            \Viserio\Component\Console\Application::class => 'get206058a713a7172158e11c9d996f6a067c294ab0356ae6697060f162e057445a',
            \Viserio\Component\Routing\Command\RouteListCommand::class => 'get5f34d750a5fcad2449cb7b81f89a57492dc2a795006c02d9b865276ad3291746',
            \Viserio\Contract\Routing\Dispatcher::class => 'get584908ff464e7559233910f9ef37cbbc81593674d92ff5b6e814b73127f8e05c',
            \Viserio\Contract\Routing\Router::class => 'get410eb27931e780eeccc23e52a6c17e0e6e2e1827d28f90c4254c8f4111788d4e',
        ];
        $this->aliases = [
            \Symfony\Component\Console\Application::class => \Viserio\Component\Console\Application::class,
            \Viserio\Component\Routing\Router::class => \Viserio\Contract\Routing\Router::class,
            'cerebro' => \Viserio\Component\Console\Application::class,
            'console' => \Viserio\Component\Console\Application::class,
            'route' => \Viserio\Contract\Routing\Router::class,
            'router' => \Viserio\Contract\Routing\Router::class,
        ];
    }

    /**
     * Returns the public Symfony\Component\Console\CommandLoader\CommandLoaderInterface shared service.
     *
     * @return \Viserio\Component\Console\CommandLoader\IteratorCommandLoader
     */
    protected function getce817e8bdc75399a693ba45b876c457a0f7fd422258f7d4eabc553987c2fbd31(): \Viserio\Component\Console\CommandLoader\IteratorCommandLoader
    {
        return $this->services[\Symfony\Component\Console\CommandLoader\CommandLoaderInterface::class] = new \Viserio\Component\Console\CommandLoader\IteratorCommandLoader(new \Viserio\Component\Container\RewindableGenerator(function () {
            yield 'route:table' => ($this->services[\Viserio\Component\Routing\Command\RouteListCommand::class] ?? $this->get5f34d750a5fcad2449cb7b81f89a57492dc2a795006c02d9b865276ad3291746());
        }, 1));
    }

    /**
     * Returns the public Viserio\Component\Console\Application shared service.
     *
     * @return \Viserio\Component\Console\Application
     */
    protected function get206058a713a7172158e11c9d996f6a067c294ab0356ae6697060f162e057445a(): \Viserio\Component\Console\Application
    {
        $this->services[\Viserio\Component\Console\Application::class] = $instance = new \Viserio\Component\Console\Application($this->getParameter('viserio.console.version'), $this->getParameter('viserio.console.name'));

        $instance->setContainer($this);
        if ($this->has(\Symfony\Component\Console\CommandLoader\CommandLoaderInterface::class)) {
            $instance->setCommandLoader(($this->services[\Symfony\Component\Console\CommandLoader\CommandLoaderInterface::class] ?? $this->getce817e8bdc75399a693ba45b876c457a0f7fd422258f7d4eabc553987c2fbd31()));
        }

        return $instance;
    }

    /**
     * Returns the public Viserio\Component\Routing\Command\RouteListCommand shared service.
     *
     * @return \Viserio\Component\Routing\Command\RouteListCommand
     */
    protected function get5f34d750a5fcad2449cb7b81f89a57492dc2a795006c02d9b865276ad3291746(): \Viserio\Component\Routing\Command\RouteListCommand
    {
        $this->services[\Viserio\Component\Routing\Command\RouteListCommand::class] = $instance = new \Viserio\Component\Routing\Command\RouteListCommand(($this->services[\Viserio\Contract\Routing\Router::class] ?? $this->get410eb27931e780eeccc23e52a6c17e0e6e2e1827d28f90c4254c8f4111788d4e()));

        $instance->setName('route:table');

        return $instance;
    }

    /**
     * Returns the public Viserio\Contract\Routing\Dispatcher shared service.
     *
     * @return \Viserio\Component\Routing\Dispatcher\MiddlewareBasedDispatcher
     */
    protected function get584908ff464e7559233910f9ef37cbbc81593674d92ff5b6e814b73127f8e05c(): \Viserio\Component\Routing\Dispatcher\MiddlewareBasedDispatcher
    {
        return $this->services[\Viserio\Contract\Routing\Dispatcher::class] = new \Viserio\Component\Routing\Dispatcher\MiddlewareBasedDispatcher();
    }

    /**
     * Returns the public Viserio\Contract\Routing\Router shared service.
     *
     * @return \Viserio\Component\Routing\Router
     */
    protected function get410eb27931e780eeccc23e52a6c17e0e6e2e1827d28f90c4254c8f4111788d4e(): \Viserio\Component\Routing\Router
    {
        $this->services[\Viserio\Contract\Routing\Router::class] = $instance = new \Viserio\Component\Routing\Router(($this->services[\Viserio\Contract\Routing\Dispatcher::class] ?? $this->get584908ff464e7559233910f9ef37cbbc81593674d92ff5b6e814b73127f8e05c()));

        $instance->setContainer($this);

        return $instance;
    }

    /**
     * {@inheritdoc}
     */
    public function getRemovedIds(): array
    {
        return [
            \Psr\Container\ContainerInterface::class => true,
            \Viserio\Contract\Container\CompiledContainer::class => true,
            \Viserio\Contract\Container\Factory::class => true,
            \Viserio\Contract\Container\TaggedContainer::class => true,
            \Viserio\Contract\Events\EventManager::class => true,
            'container' => true,
        ];
    }
}
