<?php

declare(strict_types=1);

/**
 * This file is part of Narrowspark Framework.
 *
 * (c) Daniel Bannert <d.bannert@anolilab.de>
 *
 * This source file is subject to the MIT license that is bundled
 * with this source code in the file LICENSE.
 */

namespace Container7f55f385c147561a313d666c99b5c4ad66e9aa4403c0a656b8cc9c32543648a4;

use EmptyIterator;

/**
 * This class has been auto-generated by Viserio Container Component.
 */
final class TwigServiceProviderContainer extends \Viserio\Component\Container\AbstractCompiledContainer
{
    /**
     * List of target dirs.
     *
     * @var array
     */
    private $targetDirs = [];

    /**
     * Path to the container dir.
     *
     * @var string
     */
    private $containerDir;

    /**
     * Create a new Compiled Container instance.
     *
     * @param array  $buildParameters
     * @param string $containerDir
     *
     * @var string $containerDir
     */
    public function __construct(array $buildParameters = [], string $containerDir = __DIR__)
    {
        $this->services = $this->privates = [];
        $dir = $this->targetDirs[0] = \dirname($containerDir);

        for ($i = 1; $i <= 5; $i++) {
            $this->targetDirs[$i] = $dir = \dirname($dir);
        }

        $this->containerDir = $containerDir;
        $this->parameters = \array_merge([
            'container.dumper.inline_factories' => true,
            'container.dumper.inline_class_loader' => false,
        ], $buildParameters);
        $this->methodMapping = [
            \Symfony\Component\Console\CommandLoader\CommandLoaderInterface::class => 'getce817e8bdc75399a693ba45b876c457a0f7fd422258f7d4eabc553987c2fbd31',
            \Twig\Environment::class => 'get8d9ff7a81f29c15daa148bf17605b436a0f079af45d4fe0663dc18bfb7cc9691',
            \Twig\Loader\ChainLoader::class => 'gete6b9cca367454988e84c786bc4263504862cfd0bf91cc9293b8a3c733eb3c8bb',
            \Twig\RuntimeLoader\RuntimeLoaderInterface::class => 'get7cea9b61db5e1b62f129860035f85d49ee5302a6c31f072ca310f26f4a933965',
            \Viserio\Bridge\Twig\Command\DebugCommand::class => 'get82bd7182fb48bedbde7fdb8ea705cf3720cdc161ca8374d6d8c750d55f85d419',
            \Viserio\Bridge\Twig\Command\LintCommand::class => 'getf32036d73b7c99ae4b0444626f14d4a6c18aa429903389f6fe326667f7ecec32',
            \Viserio\Component\Console\Application::class => 'get206058a713a7172158e11c9d996f6a067c294ab0356ae6697060f162e057445a',
            \Viserio\Contract\Filesystem\Filesystem::class => 'get787a79c940e7519357cde00935d657a813a0ce7c7b555cf3cb98d8c2263d18c6',
            \Viserio\Contract\View\EngineResolver::class => 'getff73b374d52eb13f0773f58273de538d62944effed5c8e2a7caa31b6d2180e5b',
            \Viserio\Contract\View\Factory::class => 'getb6b69b8c40146f590f39a23a8d000f621d6288e79e53d4fdbeae0164b92c7d63',
            \Viserio\Contract\View\Finder::class => 'get2bc187b27da90a561b690d6fd54a3000d8276c6e5b8e8167ce59a4b9355b3859',
            \Viserio\Component\OptionsResolver\Command\OptionDumpCommand::class => 'get5a73c93dbe469f9f1fae0210ee64ef2ab32ed536467d0570a89353766859bb62',
            \Viserio\Component\OptionsResolver\Command\OptionReaderCommand::class => 'get51bc2cdf2d87fcaa6a89ede54bc023ccfe784ddb4cc7a7e2be4ab3a7e9204471',
            \Viserio\Component\View\Engine\FileEngine::class => 'get1a6c73ea96b910b7c8cc9eccb8a2efd9908e964162cfa207eeef703514994b04',
            \Viserio\Component\View\Engine\PhpEngine::class => 'getd01d428260fd74997b150257850eb533cb546f9df452b1033a6c2fae22551a64',
            \Viserio\Provider\Twig\Command\CleanCommand::class => 'getb27fd541062d323461cd1a120541021d75cbc7d2bbae5eefde976856c43fbebe',
            \Viserio\Provider\Twig\Engine\TwigEngine::class => 'get60c8946331b96312aa7aa623435675475698643b927851fb2234c12cd9374ea5',
            \Viserio\Provider\Twig\Loader::class => 'get917a35e00325c34c4098b810e960473b05e7514c36627ea7d0456564e774bd56',
            'config' => 'get34bcaa5afa8745d92e6161e8495be3b939c5c6abb4dc2fd1f5a3cfdaba620256',
            'console.command.ids' => 'getdbce155f9c0e95dbd4bfbfaadab27eb79915789fa80c6c65068ccf60c9ef9e18',
        ];
        $this->uninitializedServices = [
            \Twig\Lexer::class => true,
        ];
        $this->aliases = [
            \Symfony\Component\Console\Application::class => \Viserio\Component\Console\Application::class,
            \Twig\Loader\LoaderInterface::class => \Twig\Loader\ChainLoader::class,
            \Viserio\Component\Filesystem\Filesystem::class => \Viserio\Contract\Filesystem\Filesystem::class,
            \Viserio\Component\View\ViewFactory::class => \Viserio\Contract\View\Factory::class,
            \Viserio\Component\View\ViewFinder::class => \Viserio\Contract\View\Finder::class,
            \Viserio\Provider\Twig\Command\LintCommand::class => \Viserio\Bridge\Twig\Command\LintCommand::class,
            'cerebro' => \Viserio\Component\Console\Application::class,
            'console' => \Viserio\Component\Console\Application::class,
            'files' => \Viserio\Contract\Filesystem\Filesystem::class,
            'twig' => \Twig\Environment::class,
            'view' => \Viserio\Contract\View\Factory::class,
            'view.engine.resolver' => \Viserio\Contract\View\EngineResolver::class,
            'view.finder' => \Viserio\Contract\View\Finder::class,
        ];
        $this->syntheticIds = [
            \Twig\Lexer::class => true,
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function getRemovedIds(): array
    {
        return require $this->containerDir . '/removed-ids.php';
    }

    /**
     * Returns the public Symfony\Component\Console\CommandLoader\CommandLoaderInterface shared service.
     *
     * @return \Viserio\Component\Console\CommandLoader\IteratorCommandLoader
     */
    protected function getce817e8bdc75399a693ba45b876c457a0f7fd422258f7d4eabc553987c2fbd31(): \Viserio\Component\Console\CommandLoader\IteratorCommandLoader
    {
        return $this->services[\Symfony\Component\Console\CommandLoader\CommandLoaderInterface::class] = new \Viserio\Component\Console\CommandLoader\IteratorCommandLoader(new \Viserio\Component\Container\RewindableGenerator(function () {
            yield 'twig:clear' => ($this->services[\Viserio\Provider\Twig\Command\CleanCommand::class] ?? $this->getb27fd541062d323461cd1a120541021d75cbc7d2bbae5eefde976856c43fbebe());

            yield 'twig:debug' => ($this->services[\Viserio\Bridge\Twig\Command\DebugCommand::class] ?? $this->get82bd7182fb48bedbde7fdb8ea705cf3720cdc161ca8374d6d8c750d55f85d419());

            yield 'lint:twig' => ($this->services[\Viserio\Bridge\Twig\Command\LintCommand::class] ?? $this->getf32036d73b7c99ae4b0444626f14d4a6c18aa429903389f6fe326667f7ecec32());

            yield 'option:dump' => ($this->services[\Viserio\Component\OptionsResolver\Command\OptionDumpCommand::class] ?? $this->get5a73c93dbe469f9f1fae0210ee64ef2ab32ed536467d0570a89353766859bb62());

            yield 'option:read' => ($this->services[\Viserio\Component\OptionsResolver\Command\OptionReaderCommand::class] ?? $this->get51bc2cdf2d87fcaa6a89ede54bc023ccfe784ddb4cc7a7e2be4ab3a7e9204471());
        }, 5));
    }

    /**
     * Returns the public Twig\Environment shared service.
     *
     * @return \Twig\Environment
     */
    protected function get8d9ff7a81f29c15daa148bf17605b436a0f079af45d4fe0663dc18bfb7cc9691(): \Twig\Environment
    {
        $this->services[\Twig\Environment::class] = $instance = new \Twig\Environment(($this->services[\Twig\Loader\ChainLoader::class] ?? $this->gete6b9cca367454988e84c786bc4263504862cfd0bf91cc9293b8a3c733eb3c8bb()), [
            'debug' => true,
            'cache' => '',
        ]);

        if (isset($this->services[\Twig\Lexer::class])) {
            $instance->setLexer(($this->services[\Twig\Lexer::class] ?? $this->get(\Twig\Lexer::class)));
        }

        if (isset($this->services[\Twig\RuntimeLoader\RuntimeLoaderInterface::class])) {
            $instance->addRuntimeLoader(($this->services[\Twig\RuntimeLoader\RuntimeLoaderInterface::class] ?? null));
        }
        $instance->addExtension(new \Viserio\Bridge\Twig\Extension\StrExtension());

        return $instance;
    }

    /**
     * Returns the public Twig\Loader\ChainLoader shared service.
     *
     * @return \Twig\Loader\ChainLoader
     */
    protected function gete6b9cca367454988e84c786bc4263504862cfd0bf91cc9293b8a3c733eb3c8bb(): \Twig\Loader\ChainLoader
    {
        $this->services[\Twig\Loader\ChainLoader::class] = $instance = new \Twig\Loader\ChainLoader();

        $instance->addLoader(($this->services[\Viserio\Provider\Twig\Loader::class] ?? $this->get917a35e00325c34c4098b810e960473b05e7514c36627ea7d0456564e774bd56()));

        return $instance;
    }

    /**
     * Returns the public Twig\RuntimeLoader\RuntimeLoaderInterface shared service.
     *
     * @return \Viserio\Provider\Twig\RuntimeLoader\IteratorRuntimeLoader
     */
    protected function get7cea9b61db5e1b62f129860035f85d49ee5302a6c31f072ca310f26f4a933965(): \Viserio\Provider\Twig\RuntimeLoader\IteratorRuntimeLoader
    {
        return $this->services[\Twig\RuntimeLoader\RuntimeLoaderInterface::class] = new \Viserio\Provider\Twig\RuntimeLoader\IteratorRuntimeLoader(new \Viserio\Component\Container\RewindableGenerator(static function () {
            return new EmptyIterator();
        }, 0));
    }

    /**
     * Returns the public Viserio\Bridge\Twig\Command\DebugCommand shared service.
     *
     * @return \Viserio\Bridge\Twig\Command\DebugCommand
     */
    protected function get82bd7182fb48bedbde7fdb8ea705cf3720cdc161ca8374d6d8c750d55f85d419(): \Viserio\Bridge\Twig\Command\DebugCommand
    {
        $this->services[\Viserio\Bridge\Twig\Command\DebugCommand::class] = $instance = new \Viserio\Bridge\Twig\Command\DebugCommand(($this->services[\Twig\Environment::class] ?? $this->get8d9ff7a81f29c15daa148bf17605b436a0f079af45d4fe0663dc18bfb7cc9691()));

        $instance->setName('twig:debug');

        return $instance;
    }

    /**
     * Returns the public Viserio\Bridge\Twig\Command\LintCommand shared service.
     *
     * @return \Viserio\Provider\Twig\Command\LintCommand
     */
    protected function getf32036d73b7c99ae4b0444626f14d4a6c18aa429903389f6fe326667f7ecec32(): \Viserio\Provider\Twig\Command\LintCommand
    {
        $this->services[\Viserio\Bridge\Twig\Command\LintCommand::class] = $instance = new \Viserio\Provider\Twig\Command\LintCommand(($this->services[\Twig\Environment::class] ?? $this->get8d9ff7a81f29c15daa148bf17605b436a0f079af45d4fe0663dc18bfb7cc9691()), ($this->services[\Viserio\Contract\View\Finder::class] ?? $this->get2bc187b27da90a561b690d6fd54a3000d8276c6e5b8e8167ce59a4b9355b3859()), [
            'viserio' => [
                'view' => [
                    'paths' => [
                        0 => ($this->targetDirs[2] . '/Fixture/'),
                        1 => $this->targetDirs[1],
                    ],
                    'engines' => [
                        'twig' => [
                            'options' => [
                                'debug' => true,
                                'cache' => '',
                            ],
                            'file_extension' => 'html',
                            'templates' => [
                                'test.html' => 'tests',
                            ],
                            'loaders' => [
                                0 => new \Twig\Loader\ArrayLoader(),
                            ],
                        ],
                    ],
                ],
            ],
        ]);

        $instance->setName('lint:twig');

        return $instance;
    }

    /**
     * Returns the public Viserio\Component\Console\Application shared service.
     *
     * @return \Viserio\Component\Console\Application
     */
    protected function get206058a713a7172158e11c9d996f6a067c294ab0356ae6697060f162e057445a(): \Viserio\Component\Console\Application
    {
        $this->services[\Viserio\Component\Console\Application::class] = $instance = new \Viserio\Component\Console\Application();

        $instance->setContainer($this);

        if ($this->has(\Symfony\Component\Console\CommandLoader\CommandLoaderInterface::class)) {
            $instance->setCommandLoader(($this->services[\Symfony\Component\Console\CommandLoader\CommandLoaderInterface::class] ?? $this->getce817e8bdc75399a693ba45b876c457a0f7fd422258f7d4eabc553987c2fbd31()));
        }

        return $instance;
    }

    /**
     * Returns the public Viserio\Contract\Filesystem\Filesystem shared service.
     *
     * @return \Viserio\Component\Filesystem\Filesystem
     */
    protected function get787a79c940e7519357cde00935d657a813a0ce7c7b555cf3cb98d8c2263d18c6(): \Viserio\Component\Filesystem\Filesystem
    {
        return $this->services[\Viserio\Contract\Filesystem\Filesystem::class] = new \Viserio\Component\Filesystem\Filesystem();
    }

    /**
     * Returns the public Viserio\Contract\View\EngineResolver service.
     *
     * @return \Viserio\Component\View\Engine\IteratorViewEngineLoader
     */
    protected function getff73b374d52eb13f0773f58273de538d62944effed5c8e2a7caa31b6d2180e5b(): \Viserio\Component\View\Engine\IteratorViewEngineLoader
    {
        return new \Viserio\Component\View\Engine\IteratorViewEngineLoader(new \Viserio\Component\Container\RewindableGenerator(function () {
            yield 'file' => ($this->services[\Viserio\Component\View\Engine\FileEngine::class] ?? $this->get1a6c73ea96b910b7c8cc9eccb8a2efd9908e964162cfa207eeef703514994b04());

            yield 'php' => ($this->services[\Viserio\Component\View\Engine\PhpEngine::class] ?? $this->getd01d428260fd74997b150257850eb533cb546f9df452b1033a6c2fae22551a64());

            yield 'twig' => ($this->services[\Viserio\Provider\Twig\Engine\TwigEngine::class] ?? $this->get60c8946331b96312aa7aa623435675475698643b927851fb2234c12cd9374ea5());

            yield 'html.twig' => ($this->services[\Viserio\Provider\Twig\Engine\TwigEngine::class] ?? $this->get60c8946331b96312aa7aa623435675475698643b927851fb2234c12cd9374ea5());
        }, 4));
    }

    /**
     * Returns the public Viserio\Contract\View\Factory shared service.
     *
     * @return \Viserio\Component\View\ViewFactory
     */
    protected function getb6b69b8c40146f590f39a23a8d000f621d6288e79e53d4fdbeae0164b92c7d63(): \Viserio\Component\View\ViewFactory
    {
        $this->services[\Viserio\Contract\View\Factory::class] = $instance = new \Viserio\Component\View\ViewFactory(new \Viserio\Component\View\Engine\IteratorViewEngineLoader(new \Viserio\Component\Container\RewindableGenerator(function () {
            yield 'file' => ($this->services[\Viserio\Component\View\Engine\FileEngine::class] ?? $this->get1a6c73ea96b910b7c8cc9eccb8a2efd9908e964162cfa207eeef703514994b04());

            yield 'php' => ($this->services[\Viserio\Component\View\Engine\PhpEngine::class] ?? $this->getd01d428260fd74997b150257850eb533cb546f9df452b1033a6c2fae22551a64());

            yield 'twig' => ($this->services[\Viserio\Provider\Twig\Engine\TwigEngine::class] ?? $this->get60c8946331b96312aa7aa623435675475698643b927851fb2234c12cd9374ea5());

            yield 'html.twig' => ($this->services[\Viserio\Provider\Twig\Engine\TwigEngine::class] ?? $this->get60c8946331b96312aa7aa623435675475698643b927851fb2234c12cd9374ea5());
        }, 4)), ($this->services[\Viserio\Contract\View\Finder::class] ?? $this->get2bc187b27da90a561b690d6fd54a3000d8276c6e5b8e8167ce59a4b9355b3859()));

        $instance->share('app', $this);
        $instance->addExtension('twig', 'twig');

        return $instance;
    }

    /**
     * Returns the public Viserio\Contract\View\Finder shared service.
     *
     * @return \Viserio\Component\View\ViewFinder
     */
    protected function get2bc187b27da90a561b690d6fd54a3000d8276c6e5b8e8167ce59a4b9355b3859(): \Viserio\Component\View\ViewFinder
    {
        return $this->services[\Viserio\Contract\View\Finder::class] = new \Viserio\Component\View\ViewFinder([
            'viserio' => [
                'view' => [
                    'paths' => [
                        0 => ($this->targetDirs[2] . '/Fixture/'),
                        1 => $this->targetDirs[1],
                    ],
                    'engines' => [
                        'twig' => [
                            'options' => [
                                'debug' => true,
                                'cache' => '',
                            ],
                            'file_extension' => 'html',
                            'templates' => [
                                'test.html' => 'tests',
                            ],
                            'loaders' => [
                                0 => new \Twig\Loader\ArrayLoader(),
                            ],
                        ],
                    ],
                ],
            ],
        ]);
    }

    /**
     * Returns the public Viserio\Component\OptionsResolver\Command\OptionDumpCommand shared service.
     *
     * @return \Viserio\Component\OptionsResolver\Command\OptionDumpCommand
     */
    protected function get5a73c93dbe469f9f1fae0210ee64ef2ab32ed536467d0570a89353766859bb62(): \Viserio\Component\OptionsResolver\Command\OptionDumpCommand
    {
        $this->services[\Viserio\Component\OptionsResolver\Command\OptionDumpCommand::class] = $instance = new \Viserio\Component\OptionsResolver\Command\OptionDumpCommand();

        $instance->setName('option:dump');

        return $instance;
    }

    /**
     * Returns the public Viserio\Component\OptionsResolver\Command\OptionReaderCommand shared service.
     *
     * @return \Viserio\Component\OptionsResolver\Command\OptionReaderCommand
     */
    protected function get51bc2cdf2d87fcaa6a89ede54bc023ccfe784ddb4cc7a7e2be4ab3a7e9204471(): \Viserio\Component\OptionsResolver\Command\OptionReaderCommand
    {
        $this->services[\Viserio\Component\OptionsResolver\Command\OptionReaderCommand::class] = $instance = new \Viserio\Component\OptionsResolver\Command\OptionReaderCommand();

        $instance->setName('option:read');

        return $instance;
    }

    /**
     * Returns the public Viserio\Component\View\Engine\FileEngine shared service.
     *
     * @return \Viserio\Component\View\Engine\FileEngine
     */
    protected function get1a6c73ea96b910b7c8cc9eccb8a2efd9908e964162cfa207eeef703514994b04(): \Viserio\Component\View\Engine\FileEngine
    {
        return $this->services[\Viserio\Component\View\Engine\FileEngine::class] = new \Viserio\Component\View\Engine\FileEngine();
    }

    /**
     * Returns the public Viserio\Component\View\Engine\PhpEngine shared service.
     *
     * @return \Viserio\Component\View\Engine\PhpEngine
     */
    protected function getd01d428260fd74997b150257850eb533cb546f9df452b1033a6c2fae22551a64(): \Viserio\Component\View\Engine\PhpEngine
    {
        return $this->services[\Viserio\Component\View\Engine\PhpEngine::class] = new \Viserio\Component\View\Engine\PhpEngine();
    }

    /**
     * Returns the public Viserio\Provider\Twig\Command\CleanCommand shared service.
     *
     * @return \Viserio\Provider\Twig\Command\CleanCommand
     */
    protected function getb27fd541062d323461cd1a120541021d75cbc7d2bbae5eefde976856c43fbebe(): \Viserio\Provider\Twig\Command\CleanCommand
    {
        $this->services[\Viserio\Provider\Twig\Command\CleanCommand::class] = $instance = new \Viserio\Provider\Twig\Command\CleanCommand([
            'viserio' => [
                'view' => [
                    'paths' => [
                        0 => ($this->targetDirs[2] . '/Fixture/'),
                        1 => $this->targetDirs[1],
                    ],
                    'engines' => [
                        'twig' => [
                            'options' => [
                                'debug' => true,
                                'cache' => '',
                            ],
                            'file_extension' => 'html',
                            'templates' => [
                                'test.html' => 'tests',
                            ],
                            'loaders' => [
                                0 => new \Twig\Loader\ArrayLoader(),
                            ],
                        ],
                    ],
                ],
            ],
        ]);

        $instance->setName('twig:clear');

        return $instance;
    }

    /**
     * Returns the public Viserio\Provider\Twig\Engine\TwigEngine shared service.
     *
     * @return \Viserio\Provider\Twig\Engine\TwigEngine
     */
    protected function get60c8946331b96312aa7aa623435675475698643b927851fb2234c12cd9374ea5(): \Viserio\Provider\Twig\Engine\TwigEngine
    {
        $this->services[\Viserio\Provider\Twig\Engine\TwigEngine::class] = $instance = new \Viserio\Provider\Twig\Engine\TwigEngine(($this->services[\Twig\Environment::class] ?? $this->get8d9ff7a81f29c15daa148bf17605b436a0f079af45d4fe0663dc18bfb7cc9691()), [
            'viserio' => [
                'view' => [
                    'paths' => [
                        0 => ($this->targetDirs[2] . '/Fixture/'),
                        1 => $this->targetDirs[1],
                    ],
                    'engines' => [
                        'twig' => [
                            'options' => [
                                'debug' => true,
                                'cache' => '',
                            ],
                            'file_extension' => 'html',
                            'templates' => [
                                'test.html' => 'tests',
                            ],
                            'loaders' => [
                                0 => new \Twig\Loader\ArrayLoader(),
                            ],
                        ],
                    ],
                ],
            ],
        ]);

        $instance->setContainer($this);

        return $instance;
    }

    /**
     * Returns the public Viserio\Provider\Twig\Loader shared service.
     *
     * @return \Viserio\Provider\Twig\Loader
     */
    protected function get917a35e00325c34c4098b810e960473b05e7514c36627ea7d0456564e774bd56(): \Viserio\Provider\Twig\Loader
    {
        $this->services[\Viserio\Provider\Twig\Loader::class] = $instance = new \Viserio\Provider\Twig\Loader(($this->services[\Viserio\Contract\View\Finder::class] ?? $this->get2bc187b27da90a561b690d6fd54a3000d8276c6e5b8e8167ce59a4b9355b3859()), ($this->services[\Viserio\Contract\Filesystem\Filesystem::class] ?? $this->get787a79c940e7519357cde00935d657a813a0ce7c7b555cf3cb98d8c2263d18c6()));

        $instance->setExtension('html');

        return $instance;
    }

    /**
     * Returns the public config service.
     *
     * @return array
     */
    protected function get34bcaa5afa8745d92e6161e8495be3b939c5c6abb4dc2fd1f5a3cfdaba620256(): array
    {
        return [
            'viserio' => [
                'view' => [
                    'paths' => [
                        0 => ($this->targetDirs[2] . '/Fixture/'),
                        1 => $this->targetDirs[1],
                    ],
                    'engines' => [
                        'twig' => [
                            'options' => [
                                'debug' => true,
                                'cache' => '',
                            ],
                            'file_extension' => 'html',
                            'templates' => [
                                'test.html' => 'tests',
                            ],
                            'loaders' => [
                                0 => new \Twig\Loader\ArrayLoader(),
                            ],
                        ],
                    ],
                ],
            ],
        ];
    }

    /**
     * Returns the public console.command.ids service.
     *
     * @return array
     */
    protected function getdbce155f9c0e95dbd4bfbfaadab27eb79915789fa80c6c65068ccf60c9ef9e18(): array
    {
        return [];
    }
}
