<?php

declare(strict_types=1);

namespace Viserio\Provider\Debug\Tests\Container\Provider\Compiled;

/**
 * This class has been auto-generated by Viserio Container Component.
 */
final class DebugServiceProviderContainer extends \Viserio\Component\Container\AbstractCompiledContainer
{
    /**
     * Create a new Compiled Container instance.
     */
    public function __construct()
    {
        $this->services = $this->privates = [];
        $this->methodMapping = [
            \Symfony\Component\VarDumper\Cloner\ClonerInterface::class => 'get46b8e88975048cb31b0f0045017412a8f46d2a70cdb54dc5b7c742c769237ba0',
            \Symfony\Component\VarDumper\Dumper\CliDumper::class => 'getb25ea094617df466daf029d30df67a1587315f20d8e1949c7394923e2b8c1a3e',
            \Symfony\Component\VarDumper\Dumper\DataDumperInterface::class => 'get52ff2f4e302a18ec78bae676cc3bd87ac7a5c05257e9e0d8be9be9260311b56f',
            \Symfony\Component\VarDumper\VarDumper::class => 'get4b39bfcd6c1615eaf94a5811a808827fa131f2a8ee3ca76bbc73511c8ac261e3',
            \Viserio\Component\Config\Command\ConfigDumpCommand::class => 'get88001f5d55ce57598db2e5b80611a49d605be7b037e634e18ca2493683a114ee',
            \Viserio\Component\Config\Command\ConfigReaderCommand::class => 'get91fd613885c83bb4b00b29ee3e879446444b7ecad7fdd0292ef1df30bdfa3884',
        ];
        $this->aliases = [
            \Symfony\Component\VarDumper\Cloner\VarCloner::class => \Symfony\Component\VarDumper\Cloner\ClonerInterface::class,
            \Symfony\Component\VarDumper\Dumper\HtmlDumper::class => \Symfony\Component\VarDumper\Dumper\DataDumperInterface::class,
            \Viserio\Provider\Debug\HtmlDumper::class => \Symfony\Component\VarDumper\Dumper\DataDumperInterface::class,
        ];
    }

    /**
     * Returns the public Symfony\Component\VarDumper\Cloner\ClonerInterface shared service.
     *
     * @return \Symfony\Component\VarDumper\Cloner\VarCloner
     */
    protected function get46b8e88975048cb31b0f0045017412a8f46d2a70cdb54dc5b7c742c769237ba0(): \Symfony\Component\VarDumper\Cloner\VarCloner
    {
        $this->services[\Symfony\Component\VarDumper\Cloner\ClonerInterface::class] = $instance = new \Symfony\Component\VarDumper\Cloner\VarCloner();

        $instance->setMaxItems(2500);
        $instance->setMinDepth(1);
        $instance->setMaxString(-1);
        $instance->addCasters([
            \Closure::class => 'Symfony\\Component\\VarDumper\\Caster\\ReflectionCaster::unsetClosureFileInfo',
        ]);

        return $instance;
    }

    /**
     * Returns the public Symfony\Component\VarDumper\Dumper\CliDumper shared service.
     *
     * @return \Symfony\Component\VarDumper\Dumper\CliDumper
     */
    protected function getb25ea094617df466daf029d30df67a1587315f20d8e1949c7394923e2b8c1a3e(): \Symfony\Component\VarDumper\Dumper\CliDumper
    {
        return $this->services[\Symfony\Component\VarDumper\Dumper\CliDumper::class] = new \Symfony\Component\VarDumper\Dumper\CliDumper();
    }

    /**
     * Returns the public Symfony\Component\VarDumper\Dumper\DataDumperInterface shared service.
     *
     * @return \Viserio\Provider\Debug\HtmlDumper
     */
    protected function get52ff2f4e302a18ec78bae676cc3bd87ac7a5c05257e9e0d8be9be9260311b56f(): \Viserio\Provider\Debug\HtmlDumper
    {
        $this->services[\Symfony\Component\VarDumper\Dumper\DataDumperInterface::class] = $instance = new \Viserio\Provider\Debug\HtmlDumper();

        $instance->addTheme('narrowspark', [
            'default' => 'color:#ffffff; line-height:normal; font:12px "Inconsolata", "Fira Mono", "Source Code Pro", Monaco, Consolas, "Lucida Console", monospace !important; word-wrap: break-word; white-space: pre-wrap; position:relative; z-index:99999; word-break: break-word',
            'num' => 'color:#bcd42a',
            'const' => 'color:#4bb1b1;',
            'str' => 'color:#bcd42a',
            'note' => 'color:#ef7c61',
            'ref' => 'color:#a0a0a0',
            'public' => 'color:#ffffff',
            'protected' => 'color:#ffffff',
            'private' => 'color:#ffffff',
            'meta' => 'color:#ffffff',
            'key' => 'color:#bcd42a',
            'index' => 'color:#ef7c61',
        ]);
        $instance->setTheme('narrowspark');

        return $instance;
    }

    /**
     * Returns the public Symfony\Component\VarDumper\VarDumper shared service.
     *
     * @return \Symfony\Component\VarDumper\VarDumper
     */
    protected function get4b39bfcd6c1615eaf94a5811a808827fa131f2a8ee3ca76bbc73511c8ac261e3(): \Symfony\Component\VarDumper\VarDumper
    {
        return $this->services[\Symfony\Component\VarDumper\VarDumper::class] = new \Symfony\Component\VarDumper\VarDumper();
    }

    /**
     * Returns the public Viserio\Component\Config\Command\ConfigDumpCommand shared service.
     *
     * @return \Viserio\Component\Config\Command\ConfigDumpCommand
     */
    protected function get88001f5d55ce57598db2e5b80611a49d605be7b037e634e18ca2493683a114ee(): \Viserio\Component\Config\Command\ConfigDumpCommand
    {
        return $this->services[\Viserio\Component\Config\Command\ConfigDumpCommand::class] = new \Viserio\Component\Config\Command\ConfigDumpCommand();
    }

    /**
     * Returns the public Viserio\Component\Config\Command\ConfigReaderCommand shared service.
     *
     * @return \Viserio\Component\Config\Command\ConfigReaderCommand
     */
    protected function get91fd613885c83bb4b00b29ee3e879446444b7ecad7fdd0292ef1df30bdfa3884(): \Viserio\Component\Config\Command\ConfigReaderCommand
    {
        return $this->services[\Viserio\Component\Config\Command\ConfigReaderCommand::class] = new \Viserio\Component\Config\Command\ConfigReaderCommand();
    }

    /**
     * {@inheritdoc}
     */
    public function getRemovedIds(): array
    {
        return [
            \Psr\Container\ContainerInterface::class => true,
            \Viserio\Contract\Container\CompiledContainer::class => true,
            \Viserio\Contract\Container\Factory::class => true,
            \Viserio\Contract\Container\TaggedContainer::class => true,
            'container' => true,
        ];
    }
}
