<?php

declare(strict_types=1);

/**
 * This file is part of Narrowspark Framework.
 *
 * (c) Daniel Bannert <d.bannert@anolilab.de>
 *
 * This source file is subject to the MIT license that is bundled
 * with this source code in the file LICENSE.
 */

namespace Viserio\Component\Exception\Tests\Provider\Compiled;

/**
 * This class has been auto-generated by Viserio Container Component.
 */
final class ConsoleExceptionServiceProviderContainer extends \Viserio\Component\Container\AbstractCompiledContainer
{
    /**
     * Create a new Compiled Container instance.
     */
    public function __construct()
    {
        $this->services = $this->privates = [];
        $this->methodMapping = [
            \Viserio\Contract\Exception\ConsoleHandler::class => 'geteace7a1811f2aa46e947f47dd9a20ef0a91a85aa48699c6a2f444af513904ef9',
            'config' => 'get34bcaa5afa8745d92e6161e8495be3b939c5c6abb4dc2fd1f5a3cfdaba620256',
        ];
        $this->aliases = [
            \Viserio\Component\Exception\Console\Handler::class => \Viserio\Contract\Exception\ConsoleHandler::class,
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function getRemovedIds(): array
    {
        return [
            \Psr\Container\ContainerInterface::class => true,
            \Viserio\Contract\Container\Factory::class => true,
            \Viserio\Contract\Container\TaggedContainer::class => true,
            'container' => true,
        ];
    }

    /**
     * Returns the public Viserio\Contract\Exception\ConsoleHandler shared service.
     *
     * @return \Viserio\Component\Exception\Console\Handler
     */
    protected function geteace7a1811f2aa46e947f47dd9a20ef0a91a85aa48699c6a2f444af513904ef9(): \Viserio\Component\Exception\Console\Handler
    {
        return $this->services[\Viserio\Contract\Exception\ConsoleHandler::class] = new \Viserio\Component\Exception\Console\Handler([
            'viserio' => [
                'exception' => [],
            ],
        ], null);
    }

    /**
     * Returns the public config service.
     *
     * @return array
     */
    protected function get34bcaa5afa8745d92e6161e8495be3b939c5c6abb4dc2fd1f5a3cfdaba620256(): array
    {
        return [
            'viserio' => [
                'exception' => [],
            ],
        ];
    }
}
