'Bridge: Doctrine': ["src/Viserio/Bridge/Doctrine"]
'Bridge: Monolog': ["src/Viserio/Bridge/Monolog"]
'Bridge: Twig': ["src/Viserio/Bridge/Twig"]
'Component: Bus': ["src/Viserio/Component/Bus"]
'Component: Cache': ["src/Viserio/Component/Cache"]
'Component: Console': ["src/Viserio/Component/Console"]
'Component: Container': ["src/Viserio/Component/Container"]
'Component: Cookie': ["src/Viserio/Component/Cookie"]
'Component: Cron': ["src/Viserio/Component/Cron"]
'Component: Events': ["src/Viserio/Component/Events"]
'Component: Exception': ["src/Viserio/Component/Exception"]
'Component: Filesystem': ["src/Viserio/Component/Filesystem"]
'Component: Finder': ["src/Viserio/Component/Finder"]
'Component: Foundation': ["src/Viserio/Component/Foundation"]
'Component: Http': ["src/Viserio/Component/Http"]
'Component: Http Factory': ["src/Viserio/Component/HttpFactory"]
'Component: Http Foundation': ["src/Viserio/Component/HttpFoundation"]
'Component: Log': ["src/Viserio/Component/Log"]
'Component: Mail': ["src/Viserio/Component/Mail"]
'Component: Manager': ["src/Viserio/Component/Manager"]
'Component: Options Resolver': ["src/Viserio/Component/Config"]
'Component: Pagination': ["src/Viserio/Component/Pagination"]
'Component: Parser': ["src/Viserio/Component/Parser"]
'Component: Path': ["src/Viserio/Component/Path"]
'Component: Pipeline': ["src/Viserio/Component/Pipeline"]
'Component: Profiler': ["src/Viserio/Component/Profiler"]
'Component: Routing': ["src/Viserio/Component/Routing"]
'Component: Session': ["src/Viserio/Component/Session"]
'Component: Support': ["src/Viserio/Component/Support"]
'Component: Translation': ["src/Viserio/Component/Translation"]
'Component: Validation': ["src/Viserio/Component/Validation"]
'Component: View': ["src/Viserio/Component/View"]
'Component: Web Server': ["src/Viserio/Component/WebServer"]
'Provider: Debug': ["src/Viserio/Provider/Debug"]
'Provider: Framework': ["src/Viserio/Provider/Framework"]
'Provider: Twig': ["src/Viserio/Provider/Twig"]
