filter:
  paths: ["src/Viserio/*"]
  excluded_paths:
    - "src/Viserio/*/Tests/*"
    - "vendor/*"
    - "src/Viserio/*/phpunit.xml.dist"

build:
  environment:
      php: '5.6'
  dependencies:
      override:
        - 'composer install'
  tests:
        override:
          - command: ''

tools:
  external_code_coverage:
    timeout: 600
    runs: 3
