preset: psr2

risky: false

linting: true

enabled:
  - concat_with_spaces
  - function_typehint_space
  - newline_after_open_tag
  - no_blank_lines_before_namespace
  - ordered_use
  - phpdoc_order
  - short_array_syntax
  - alias_functions
  - array_element_no_space_before_comma
  - array_element_white_space_after_comma
  - double_arrow_multiline_whitespaces
  - duplicate_semicolon
  - empty_return
  - extra_empty_lines
  - include
  - list_commas
  - method_separation
  - multiline_array_trailing_comma
  - namespace_no_leading_whitespace
  - new_with_braces
  - no_blank_lines_after_class_opening
  - no_empty_lines_after_phpdocs
  - object_operator
  - operators_spaces
  - phpdoc_align
  - phpdoc_indent
  - phpdoc_inline_tag
  - phpdoc_no_access
  - phpdoc_no_empty_return
  - phpdoc_no_package
  - phpdoc_scalar
  - phpdoc_separation
  - phpdoc_to_comment
  - phpdoc_trim
  - phpdoc_types
  - phpdoc_type_to_var
  - phpdoc_var_without_name
  - remove_leading_slash_use
  - return
  - short_bool_cast
  - single_array_no_trailing_comma
  - single_quote
  - spaces_after_semicolon
  - spaces_before_semicolon
  - spaces_cast
  - standardize_not_equal
  - ternary_spaces
  - trim_array_spaces
  - unneeded_control_parentheses
  - whitespacy_lines

finder:
  exclude:
    - "build"
    - "vendor"
    - "tests"
  name:
    - "*.php"
