version: '3'
services:
  php73_32:
    build:
      context: ./.docker/php/32bit/
      args:
        PHP_VERSION: "7.3.0"
        XDEBUG_VERSION: "2.7.0beta1"
        INSTALL_XDEBUG: "false"
        INSTALL_CODING_STANDARD: "true"
    expose:
      - 9000
    volumes:
      - .:/var/www/framework
    links:
      - mysql
      - redis
    tty: true

  mysql:
    image: mysql:latest
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test

  redis:
    image: redis:latest
    expose:
      - 6379
