version: '3'
services:
  php73_32:
    build:
      context: ./.docker/php/
      args:
        NAMESPACE: "i386/php"
        PHP_VERSION: "7.4.2"
        XDEBUG_VERSION: "2.9.0"
        INSTALL_XDEBUG: "false"
    expose:
      - 9000
    volumes:
      - data:/var/www/framework
    links:
      - mysql
      - redis
    tty: true

  mysql:
    image: mysql:latest
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test

  redis:
    image: redis:latest
    expose:
      - 6379

volumes:
  data:
    driver: lebokus/bindfs:latest
    driver_opts:
      sourcePath: "${PWD}"
      map: "${UID}/0:@${UID}/@0"
