<?php

declare(strict_types=1);

/**
 * This file is part of Narrowspark Framework.
 *
 * (c) Daniel Bannert <d.bannert@anolilab.de>
 *
 * This source file is subject to the MIT license that is bundled
 * with this source code in the file LICENSE.
 */

namespace Viserio\Component\Filesystem\Tests\Container\Provider\Compiled;

/**
 * This class has been auto-generated by Viserio Container Component.
 */
if (\class_exists(\Container357b7101a416c18e5a4588e2afb3aaf32c2c7614bdf52f79057f621d2fb795b0\FilesystemServiceProviderContainer::class, false)) {
    // no-op
} elseif (! include __DIR__ . '/Container357b7101a416c18e5a4588e2afb3aaf32c2c7614bdf52f79057f621d2fb795b0/FilesystemServiceProviderContainer.php') {
    \touch(__DIR__ . '/Container357b7101a416c18e5a4588e2afb3aaf32c2c7614bdf52f79057f621d2fb795b0.legacy');

    return;
}

if (! \class_exists(FilesystemServiceProviderContainer::class, false)) {
    \class_alias(\Container357b7101a416c18e5a4588e2afb3aaf32c2c7614bdf52f79057f621d2fb795b0\FilesystemServiceProviderContainer::class, FilesystemServiceProviderContainer::class, false);
}

return new \Container357b7101a416c18e5a4588e2afb3aaf32c2c7614bdf52f79057f621d2fb795b0\FilesystemServiceProviderContainer([
    'container.build_hash' => '357b7101a416c18e5a4588e2afb3aaf32c2c7614bdf52f79057f621d2fb795b0',
    'container.build_id' => 'ae601269',
    'container.build_time' => 1565454394,
], __DIR__ . '/Container357b7101a416c18e5a4588e2afb3aaf32c2c7614bdf52f79057f621d2fb795b0');
