<?php

declare(strict_types=1);

/**
 * This file is part of Narrowspark Framework.
 *
 * (c) Daniel Bannert <d.bannert@anolilab.de>
 *
 * This source file is subject to the MIT license that is bundled
 * with this source code in the file LICENSE.
 */

namespace Container739e609bece4abe5487ae03b6cccaedded684317c476955347c4fabd1fa62276;

use Parsedown;

/**
 * This class has been auto-generated by Viserio Container Component.
 */
final class HttpExceptionServiceProviderContainer extends \Viserio\Component\Container\AbstractCompiledContainer
{
    /**
     * List of target dirs.
     *
     * @var array
     */
    private $targetDirs = [];

    /**
     * Path to the container dir.
     *
     * @var string
     */
    private $containerDir;

    /**
     * Create a new Compiled Container instance.
     *
     * @param array  $buildParameters
     * @param string $containerDir
     *
     * @var string $containerDir
     */
    public function __construct(array $buildParameters = [], string $containerDir = __DIR__)
    {
        $this->services = $this->privates = [];
        $dir = $this->targetDirs[0] = \dirname($containerDir);

        for ($i = 1; $i <= 5; $i++) {
            $this->targetDirs[$i] = $dir = \dirname($dir);
        }

        $this->containerDir = $containerDir;
        $this->parameters = \array_merge([
            'viserio.container.dumper.inline_factories' => true,
            'viserio.container.dumper.inline_class_loader' => false,
        ], $buildParameters);
        $this->methodMapping = [
            \Psr\Http\Message\RequestFactoryInterface::class => 'getef97f0bcda07c062701f26c9b3469bc1cc5d4e690f06f38d62089dcd523e5878',
            \Psr\Http\Message\ResponseFactoryInterface::class => 'get2d91ce2b646e11cd19e34bcc1c7ac36869d3c26f204ab659c91ddaacfcf7a387',
            \Psr\Http\Message\ServerRequestFactoryInterface::class => 'get7087ed87890b3b08220b4aa3de8f288397365878109fe8d4fb5deff3658ce6f1',
            \Psr\Http\Message\StreamFactoryInterface::class => 'getf55873d449ac864fac76bef8b64ad9303cdec09695e157278c9239bd952475bf',
            \Psr\Http\Message\UploadedFileFactoryInterface::class => 'get4e26902efbb16d7b57d6675c0e728f470fe403dde66b42fa75c8da91885c8976',
            \Psr\Http\Message\UriFactoryInterface::class => 'get6efc5ddbff5b9d058c48b4514c1f9ea8e4e3006a3fab6a03b46065a08a86260d',
            \Psr\Log\LoggerInterface::class => 'get7b41cd3c0d8842e9337c4046b9fdcc1a2972a75ad8af646b65f2ee2d3f1daba0',
            \Viserio\Component\Config\Command\ConfigCacheCommand::class => 'get84d58a3ba822be935850e8e8481cdf2592d8673d55a6e2f8c70316ee6bbb319d',
            \Viserio\Component\Config\Command\ConfigClearCommand::class => 'get0bd786dbe8504de8d66c9c21f2058290fbd2c0a337e5e946746a21d611703ed4',
            \Viserio\Contract\Config\Repository::class => 'getdf1c31fe4ba52c5a58984206611ddc1ed0e532dc8d86e860064543054d395666',
            \Viserio\Contract\Exception\HttpHandler::class => 'get11f960196346b7de2752efaf3501574c92bb813669a8f1ddbdc29080d25b2fd0',
            \Viserio\Contract\Filesystem\Filesystem::class => 'get787a79c940e7519357cde00935d657a813a0ce7c7b555cf3cb98d8c2263d18c6',
            \Viserio\Contract\View\EngineResolver::class => 'getff73b374d52eb13f0773f58273de538d62944effed5c8e2a7caa31b6d2180e5b',
            \Viserio\Contract\View\Factory::class => 'getb6b69b8c40146f590f39a23a8d000f621d6288e79e53d4fdbeae0164b92c7d63',
            \Viserio\Contract\View\Finder::class => 'get2bc187b27da90a561b690d6fd54a3000d8276c6e5b8e8167ce59a4b9355b3859',
            \Viserio\Component\Exception\Displayer\HtmlDisplayer::class => 'get726f0f4822126fe34d8dd6c789a4c704fbc3fd47d9383be3dcad35053cc0ddd5',
            \Viserio\Component\Exception\Displayer\JsonApiDisplayer::class => 'get0570c496c73f0789f1cdcb8ce742bac9fe3e2d8a0f4b4d7df5975154eaeb1755',
            \Viserio\Component\Exception\Displayer\JsonDisplayer::class => 'getbe647055a30710a69a0fbc6ca5d8670e371102e1995f4b55bfbdc9ddcd38408b',
            \Viserio\Component\Exception\Displayer\SymfonyDisplayer::class => 'getea6b397a7ae7be4837777675a0a530d8584cd62dcedc294270a91ece05a52cb1',
            \Viserio\Component\Exception\Displayer\ViewDisplayer::class => 'get6856640d8556ceaddfb068c0d9e63d966e86ea25a7d36271617f096bfd1b89c0',
            \Viserio\Component\Exception\Displayer\WhoopsJsonDisplayer::class => 'getc4fd027299e55dea6c2be758c50578976d0bae4b10bb8f527eaffe458339abbd',
            \Viserio\Component\Exception\Displayer\WhoopsPrettyDisplayer::class => 'get26256455ca4acbf682bcbeea0c15c7935f5010a43e6720405ce766e0ee4fcbd6',
            \Viserio\Component\Exception\Filter\CanDisplayFilter::class => 'getd96c2338fb2fff6074761db439dd2c13b9305fc3db397f6dd55054e47a0895c3',
            \Viserio\Component\Exception\Filter\ContentTypeFilter::class => 'get08d2945e80d03d32cb8abe1dc615517acd686526a87c0afcc93a0fdf5204f355',
            \Viserio\Component\Exception\Filter\VerboseFilter::class => 'get90d6500a6c35de72475ff2df52f6923ac58ae0eea0f173b0f931c854f41939fd',
            \Viserio\Component\Log\LogManager::class => 'getafab5c05bf2396b9796ebb692ff953a79f0a908d696ed0ac4d3e3657b06421c1',
            \Viserio\Component\View\Engine\FileEngine::class => 'get1a6c73ea96b910b7c8cc9eccb8a2efd9908e964162cfa207eeef703514994b04',
            \Viserio\Component\View\Engine\MarkdownEngine::class => 'get198642be4740f0701f2a66d050b91dc830dda7c7647fc3ed590cde395b592d96',
            \Viserio\Component\View\Engine\PhpEngine::class => 'getd01d428260fd74997b150257850eb533cb546f9df452b1033a6c2fae22551a64',
        ];
        $this->aliases = [
            \Viserio\Component\Config\Repository::class => \Viserio\Contract\Config\Repository::class,
            \Viserio\Component\Exception\Http\Handler::class => \Viserio\Contract\Exception\HttpHandler::class,
            \Viserio\Component\Filesystem\Filesystem::class => \Viserio\Contract\Filesystem\Filesystem::class,
            \Viserio\Component\HttpFactory\RequestFactory::class => \Psr\Http\Message\RequestFactoryInterface::class,
            \Viserio\Component\HttpFactory\ResponseFactory::class => \Psr\Http\Message\ResponseFactoryInterface::class,
            \Viserio\Component\HttpFactory\ServerRequestFactory::class => \Psr\Http\Message\ServerRequestFactoryInterface::class,
            \Viserio\Component\HttpFactory\StreamFactory::class => \Psr\Http\Message\StreamFactoryInterface::class,
            \Viserio\Component\HttpFactory\UploadedFileFactory::class => \Psr\Http\Message\UploadedFileFactoryInterface::class,
            \Viserio\Component\HttpFactory\UriFactory::class => \Psr\Http\Message\UriFactoryInterface::class,
            \Viserio\Component\View\ViewFactory::class => \Viserio\Contract\View\Factory::class,
            \Viserio\Component\View\ViewFinder::class => \Viserio\Contract\View\Finder::class,
            'config' => \Viserio\Contract\Config\Repository::class,
            'files' => \Viserio\Contract\Filesystem\Filesystem::class,
            'log' => \Viserio\Component\Log\LogManager::class,
            'view' => \Viserio\Contract\View\Factory::class,
            'view.engine.resolver' => \Viserio\Contract\View\EngineResolver::class,
            'view.finder' => \Viserio\Contract\View\Finder::class,
        ];
        $this->syntheticIds = [
            Parsedown::class => true,
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function getRemovedIds(): array
    {
        return require $this->containerDir . '/removed-ids.php';
    }

    /**
     * Returns the public Psr\Http\Message\RequestFactoryInterface shared service.
     *
     * @return \Viserio\Component\HttpFactory\RequestFactory
     */
    protected function getef97f0bcda07c062701f26c9b3469bc1cc5d4e690f06f38d62089dcd523e5878(): \Viserio\Component\HttpFactory\RequestFactory
    {
        return $this->services[\Psr\Http\Message\RequestFactoryInterface::class] = new \Viserio\Component\HttpFactory\RequestFactory();
    }

    /**
     * Returns the public Psr\Http\Message\ResponseFactoryInterface shared service.
     *
     * @return \Viserio\Component\HttpFactory\ResponseFactory
     */
    protected function get2d91ce2b646e11cd19e34bcc1c7ac36869d3c26f204ab659c91ddaacfcf7a387(): \Viserio\Component\HttpFactory\ResponseFactory
    {
        return $this->services[\Psr\Http\Message\ResponseFactoryInterface::class] = new \Viserio\Component\HttpFactory\ResponseFactory();
    }

    /**
     * Returns the public Psr\Http\Message\ServerRequestFactoryInterface shared service.
     *
     * @return \Viserio\Component\HttpFactory\ServerRequestFactory
     */
    protected function get7087ed87890b3b08220b4aa3de8f288397365878109fe8d4fb5deff3658ce6f1(): \Viserio\Component\HttpFactory\ServerRequestFactory
    {
        return $this->services[\Psr\Http\Message\ServerRequestFactoryInterface::class] = new \Viserio\Component\HttpFactory\ServerRequestFactory();
    }

    /**
     * Returns the public Psr\Http\Message\StreamFactoryInterface shared service.
     *
     * @return \Viserio\Component\HttpFactory\StreamFactory
     */
    protected function getf55873d449ac864fac76bef8b64ad9303cdec09695e157278c9239bd952475bf(): \Viserio\Component\HttpFactory\StreamFactory
    {
        return $this->services[\Psr\Http\Message\StreamFactoryInterface::class] = new \Viserio\Component\HttpFactory\StreamFactory();
    }

    /**
     * Returns the public Psr\Http\Message\UploadedFileFactoryInterface shared service.
     *
     * @return \Viserio\Component\HttpFactory\UploadedFileFactory
     */
    protected function get4e26902efbb16d7b57d6675c0e728f470fe403dde66b42fa75c8da91885c8976(): \Viserio\Component\HttpFactory\UploadedFileFactory
    {
        return $this->services[\Psr\Http\Message\UploadedFileFactoryInterface::class] = new \Viserio\Component\HttpFactory\UploadedFileFactory();
    }

    /**
     * Returns the public Psr\Http\Message\UriFactoryInterface shared service.
     *
     * @return \Viserio\Component\HttpFactory\UriFactory
     */
    protected function get6efc5ddbff5b9d058c48b4514c1f9ea8e4e3006a3fab6a03b46065a08a86260d(): \Viserio\Component\HttpFactory\UriFactory
    {
        return $this->services[\Psr\Http\Message\UriFactoryInterface::class] = new \Viserio\Component\HttpFactory\UriFactory();
    }

    /**
     * Returns the public Psr\Log\LoggerInterface shared service.
     *
     * @return mixed An instance returned by \Viserio\Component\Container\Definition\ReferenceDefinition::getDriver()
     */
    protected function get7b41cd3c0d8842e9337c4046b9fdcc1a2972a75ad8af646b65f2ee2d3f1daba0()
    {
        return $this->services[\Psr\Log\LoggerInterface::class] = ($this->services[\Viserio\Component\Log\LogManager::class] ?? $this->getafab5c05bf2396b9796ebb692ff953a79f0a908d696ed0ac4d3e3657b06421c1())->getDriver();
    }

    /**
     * Returns the public Viserio\Component\Config\Command\ConfigCacheCommand shared service.
     *
     * @return \Viserio\Component\Config\Command\ConfigCacheCommand
     */
    protected function get84d58a3ba822be935850e8e8481cdf2592d8673d55a6e2f8c70316ee6bbb319d(): \Viserio\Component\Config\Command\ConfigCacheCommand
    {
        return $this->services[\Viserio\Component\Config\Command\ConfigCacheCommand::class] = new \Viserio\Component\Config\Command\ConfigCacheCommand();
    }

    /**
     * Returns the public Viserio\Component\Config\Command\ConfigClearCommand shared service.
     *
     * @return \Viserio\Component\Config\Command\ConfigClearCommand
     */
    protected function get0bd786dbe8504de8d66c9c21f2058290fbd2c0a337e5e946746a21d611703ed4(): \Viserio\Component\Config\Command\ConfigClearCommand
    {
        return $this->services[\Viserio\Component\Config\Command\ConfigClearCommand::class] = new \Viserio\Component\Config\Command\ConfigClearCommand();
    }

    /**
     * Returns the public Viserio\Contract\Config\Repository shared service.
     *
     * @return \Viserio\Component\Config\Repository
     */
    protected function getdf1c31fe4ba52c5a58984206611ddc1ed0e532dc8d86e860064543054d395666(): \Viserio\Component\Config\Repository
    {
        $this->services[\Viserio\Contract\Config\Repository::class] = $instance = new \Viserio\Component\Config\Repository();

        $instance->addParameterProcessor(new \Viserio\Component\Config\Processor\EnvParameterProcessor());
        $instance->setArray([
            'viserio' => [
                'exception' => [
                    'env' => 'dev',
                    'debug' => false,
                    'http' => [
                        'default_displayer' => '',
                    ],
                ],
                'view' => [
                    'paths' => [],
                ],
                'logging' => [
                    'env' => 'dev',
                    'path' => $this->targetDirs[1],
                ],
            ],
        ]);

        return $instance;
    }

    /**
     * Returns the public Viserio\Contract\Exception\HttpHandler shared service.
     *
     * @return \Viserio\Component\Exception\Http\Handler
     */
    protected function get11f960196346b7de2752efaf3501574c92bb813669a8f1ddbdc29080d25b2fd0(): \Viserio\Component\Exception\Http\Handler
    {
        $this->services[\Viserio\Contract\Exception\HttpHandler::class] = $instance = new \Viserio\Component\Exception\Http\Handler(($this->services[\Viserio\Contract\Config\Repository::class] ?? $this->getdf1c31fe4ba52c5a58984206611ddc1ed0e532dc8d86e860064543054d395666()), ($this->services[\Psr\Http\Message\ResponseFactoryInterface::class] ?? $this->get2d91ce2b646e11cd19e34bcc1c7ac36869d3c26f204ab659c91ddaacfcf7a387()), ($this->services[\Psr\Log\LoggerInterface::class] ?? $this->get7b41cd3c0d8842e9337c4046b9fdcc1a2972a75ad8af646b65f2ee2d3f1daba0()));

        $instance->addFilter(($this->services[\Viserio\Component\Exception\Filter\VerboseFilter::class] ?? $this->get90d6500a6c35de72475ff2df52f6923ac58ae0eea0f173b0f931c854f41939fd()), 32);
        $instance->addFilter(($this->services[\Viserio\Component\Exception\Filter\CanDisplayFilter::class] ?? $this->getd96c2338fb2fff6074761db439dd2c13b9305fc3db397f6dd55054e47a0895c3()), 64);
        $instance->addFilter(($this->services[\Viserio\Component\Exception\Filter\ContentTypeFilter::class] ?? $this->get08d2945e80d03d32cb8abe1dc615517acd686526a87c0afcc93a0fdf5204f355()), 128);
        $instance->addDisplayer(($this->services[\Viserio\Component\Exception\Displayer\SymfonyDisplayer::class] ?? $this->getea6b397a7ae7be4837777675a0a530d8584cd62dcedc294270a91ece05a52cb1()), 64);
        $instance->addDisplayer(($this->services[\Viserio\Component\Exception\Displayer\HtmlDisplayer::class] ?? $this->get726f0f4822126fe34d8dd6c789a4c704fbc3fd47d9383be3dcad35053cc0ddd5()), 256);
        $instance->addDisplayer(($this->services[\Viserio\Component\Exception\Displayer\JsonDisplayer::class] ?? $this->getbe647055a30710a69a0fbc6ca5d8670e371102e1995f4b55bfbdc9ddcd38408b()), 1024);
        $instance->addDisplayer(($this->services[\Viserio\Component\Exception\Displayer\JsonApiDisplayer::class] ?? $this->get0570c496c73f0789f1cdcb8ce742bac9fe3e2d8a0f4b4d7df5975154eaeb1755()), 2048);
        $instance->addDisplayer(($this->services[\Viserio\Component\Exception\Displayer\ViewDisplayer::class] ?? $this->get6856640d8556ceaddfb068c0d9e63d966e86ea25a7d36271617f096bfd1b89c0()), 128);
        $instance->addDisplayer(($this->services[\Viserio\Component\Exception\Displayer\WhoopsPrettyDisplayer::class] ?? $this->get26256455ca4acbf682bcbeea0c15c7935f5010a43e6720405ce766e0ee4fcbd6()), 32);
        $instance->addDisplayer(($this->services[\Viserio\Component\Exception\Displayer\WhoopsJsonDisplayer::class] ?? $this->getc4fd027299e55dea6c2be758c50578976d0bae4b10bb8f527eaffe458339abbd()), 512);

        return $instance;
    }

    /**
     * Returns the public Viserio\Contract\Filesystem\Filesystem shared service.
     *
     * @return \Viserio\Component\Filesystem\Filesystem
     */
    protected function get787a79c940e7519357cde00935d657a813a0ce7c7b555cf3cb98d8c2263d18c6(): \Viserio\Component\Filesystem\Filesystem
    {
        return $this->services[\Viserio\Contract\Filesystem\Filesystem::class] = new \Viserio\Component\Filesystem\Filesystem();
    }

    /**
     * Returns the public Viserio\Contract\View\EngineResolver service.
     *
     * @return \Viserio\Component\View\Engine\IteratorViewEngineLoader
     */
    protected function getff73b374d52eb13f0773f58273de538d62944effed5c8e2a7caa31b6d2180e5b(): \Viserio\Component\View\Engine\IteratorViewEngineLoader
    {
        return new \Viserio\Component\View\Engine\IteratorViewEngineLoader(new \Viserio\Component\Container\RewindableGenerator(function () {
            yield 'file' => ($this->services[\Viserio\Component\View\Engine\FileEngine::class] ?? $this->get1a6c73ea96b910b7c8cc9eccb8a2efd9908e964162cfa207eeef703514994b04());

            yield 'php' => ($this->services[\Viserio\Component\View\Engine\PhpEngine::class] ?? $this->getd01d428260fd74997b150257850eb533cb546f9df452b1033a6c2fae22551a64());

            yield 'md' => ($this->services[\Viserio\Component\View\Engine\MarkdownEngine::class] ?? $this->get198642be4740f0701f2a66d050b91dc830dda7c7647fc3ed590cde395b592d96());
        }, 3));
    }

    /**
     * Returns the public Viserio\Contract\View\Factory shared service.
     *
     * @return \Viserio\Component\View\ViewFactory
     */
    protected function getb6b69b8c40146f590f39a23a8d000f621d6288e79e53d4fdbeae0164b92c7d63(): \Viserio\Component\View\ViewFactory
    {
        $this->services[\Viserio\Contract\View\Factory::class] = $instance = new \Viserio\Component\View\ViewFactory(new \Viserio\Component\View\Engine\IteratorViewEngineLoader(new \Viserio\Component\Container\RewindableGenerator(function () {
            yield 'file' => ($this->services[\Viserio\Component\View\Engine\FileEngine::class] ?? $this->get1a6c73ea96b910b7c8cc9eccb8a2efd9908e964162cfa207eeef703514994b04());

            yield 'php' => ($this->services[\Viserio\Component\View\Engine\PhpEngine::class] ?? $this->getd01d428260fd74997b150257850eb533cb546f9df452b1033a6c2fae22551a64());

            yield 'md' => ($this->services[\Viserio\Component\View\Engine\MarkdownEngine::class] ?? $this->get198642be4740f0701f2a66d050b91dc830dda7c7647fc3ed590cde395b592d96());
        }, 3)), ($this->services[\Viserio\Contract\View\Finder::class] ?? $this->get2bc187b27da90a561b690d6fd54a3000d8276c6e5b8e8167ce59a4b9355b3859()));

        $instance->share('app', $this);

        return $instance;
    }

    /**
     * Returns the public Viserio\Contract\View\Finder shared service.
     *
     * @return \Viserio\Component\View\ViewFinder
     */
    protected function get2bc187b27da90a561b690d6fd54a3000d8276c6e5b8e8167ce59a4b9355b3859(): \Viserio\Component\View\ViewFinder
    {
        return $this->services[\Viserio\Contract\View\Finder::class] = new \Viserio\Component\View\ViewFinder(($this->services[\Viserio\Contract\Config\Repository::class] ?? $this->getdf1c31fe4ba52c5a58984206611ddc1ed0e532dc8d86e860064543054d395666()));
    }

    /**
     * Returns the public Viserio\Component\Exception\Displayer\HtmlDisplayer shared service.
     *
     * @return \Viserio\Component\Exception\Displayer\HtmlDisplayer
     */
    protected function get726f0f4822126fe34d8dd6c789a4c704fbc3fd47d9383be3dcad35053cc0ddd5(): \Viserio\Component\Exception\Displayer\HtmlDisplayer
    {
        return $this->services[\Viserio\Component\Exception\Displayer\HtmlDisplayer::class] = new \Viserio\Component\Exception\Displayer\HtmlDisplayer(($this->services[\Psr\Http\Message\ResponseFactoryInterface::class] ?? $this->get2d91ce2b646e11cd19e34bcc1c7ac36869d3c26f204ab659c91ddaacfcf7a387()), ($this->services[\Viserio\Contract\Config\Repository::class] ?? $this->getdf1c31fe4ba52c5a58984206611ddc1ed0e532dc8d86e860064543054d395666()));
    }

    /**
     * Returns the public Viserio\Component\Exception\Displayer\JsonApiDisplayer shared service.
     *
     * @return \Viserio\Component\Exception\Displayer\JsonApiDisplayer
     */
    protected function get0570c496c73f0789f1cdcb8ce742bac9fe3e2d8a0f4b4d7df5975154eaeb1755(): \Viserio\Component\Exception\Displayer\JsonApiDisplayer
    {
        return $this->services[\Viserio\Component\Exception\Displayer\JsonApiDisplayer::class] = new \Viserio\Component\Exception\Displayer\JsonApiDisplayer(($this->services[\Psr\Http\Message\ResponseFactoryInterface::class] ?? $this->get2d91ce2b646e11cd19e34bcc1c7ac36869d3c26f204ab659c91ddaacfcf7a387()));
    }

    /**
     * Returns the public Viserio\Component\Exception\Displayer\JsonDisplayer shared service.
     *
     * @return \Viserio\Component\Exception\Displayer\JsonDisplayer
     */
    protected function getbe647055a30710a69a0fbc6ca5d8670e371102e1995f4b55bfbdc9ddcd38408b(): \Viserio\Component\Exception\Displayer\JsonDisplayer
    {
        return $this->services[\Viserio\Component\Exception\Displayer\JsonDisplayer::class] = new \Viserio\Component\Exception\Displayer\JsonDisplayer(($this->services[\Psr\Http\Message\ResponseFactoryInterface::class] ?? $this->get2d91ce2b646e11cd19e34bcc1c7ac36869d3c26f204ab659c91ddaacfcf7a387()));
    }

    /**
     * Returns the public Viserio\Component\Exception\Displayer\SymfonyDisplayer shared service.
     *
     * @return \Viserio\Component\Exception\Displayer\SymfonyDisplayer
     */
    protected function getea6b397a7ae7be4837777675a0a530d8584cd62dcedc294270a91ece05a52cb1(): \Viserio\Component\Exception\Displayer\SymfonyDisplayer
    {
        return $this->services[\Viserio\Component\Exception\Displayer\SymfonyDisplayer::class] = new \Viserio\Component\Exception\Displayer\SymfonyDisplayer(($this->services[\Psr\Http\Message\ResponseFactoryInterface::class] ?? $this->get2d91ce2b646e11cd19e34bcc1c7ac36869d3c26f204ab659c91ddaacfcf7a387()), ($this->services[\Viserio\Contract\Config\Repository::class] ?? $this->getdf1c31fe4ba52c5a58984206611ddc1ed0e532dc8d86e860064543054d395666()));
    }

    /**
     * Returns the public Viserio\Component\Exception\Displayer\ViewDisplayer shared service.
     *
     * @return \Viserio\Component\Exception\Displayer\ViewDisplayer
     */
    protected function get6856640d8556ceaddfb068c0d9e63d966e86ea25a7d36271617f096bfd1b89c0(): \Viserio\Component\Exception\Displayer\ViewDisplayer
    {
        return $this->services[\Viserio\Component\Exception\Displayer\ViewDisplayer::class] = new \Viserio\Component\Exception\Displayer\ViewDisplayer(($this->services[\Psr\Http\Message\ResponseFactoryInterface::class] ?? $this->get2d91ce2b646e11cd19e34bcc1c7ac36869d3c26f204ab659c91ddaacfcf7a387()), ($this->services[\Viserio\Contract\View\Factory::class] ?? $this->getb6b69b8c40146f590f39a23a8d000f621d6288e79e53d4fdbeae0164b92c7d63()));
    }

    /**
     * Returns the public Viserio\Component\Exception\Displayer\WhoopsJsonDisplayer shared service.
     *
     * @return \Viserio\Component\Exception\Displayer\WhoopsJsonDisplayer
     */
    protected function getc4fd027299e55dea6c2be758c50578976d0bae4b10bb8f527eaffe458339abbd(): \Viserio\Component\Exception\Displayer\WhoopsJsonDisplayer
    {
        return $this->services[\Viserio\Component\Exception\Displayer\WhoopsJsonDisplayer::class] = new \Viserio\Component\Exception\Displayer\WhoopsJsonDisplayer(($this->services[\Psr\Http\Message\ResponseFactoryInterface::class] ?? $this->get2d91ce2b646e11cd19e34bcc1c7ac36869d3c26f204ab659c91ddaacfcf7a387()));
    }

    /**
     * Returns the public Viserio\Component\Exception\Displayer\WhoopsPrettyDisplayer shared service.
     *
     * @return \Viserio\Component\Exception\Displayer\WhoopsPrettyDisplayer
     */
    protected function get26256455ca4acbf682bcbeea0c15c7935f5010a43e6720405ce766e0ee4fcbd6(): \Viserio\Component\Exception\Displayer\WhoopsPrettyDisplayer
    {
        return $this->services[\Viserio\Component\Exception\Displayer\WhoopsPrettyDisplayer::class] = new \Viserio\Component\Exception\Displayer\WhoopsPrettyDisplayer(($this->services[\Psr\Http\Message\ResponseFactoryInterface::class] ?? $this->get2d91ce2b646e11cd19e34bcc1c7ac36869d3c26f204ab659c91ddaacfcf7a387()), ($this->services[\Viserio\Contract\Config\Repository::class] ?? $this->getdf1c31fe4ba52c5a58984206611ddc1ed0e532dc8d86e860064543054d395666()));
    }

    /**
     * Returns the public Viserio\Component\Exception\Filter\CanDisplayFilter shared service.
     *
     * @return \Viserio\Component\Exception\Filter\CanDisplayFilter
     */
    protected function getd96c2338fb2fff6074761db439dd2c13b9305fc3db397f6dd55054e47a0895c3(): \Viserio\Component\Exception\Filter\CanDisplayFilter
    {
        return $this->services[\Viserio\Component\Exception\Filter\CanDisplayFilter::class] = new \Viserio\Component\Exception\Filter\CanDisplayFilter();
    }

    /**
     * Returns the public Viserio\Component\Exception\Filter\ContentTypeFilter shared service.
     *
     * @return \Viserio\Component\Exception\Filter\ContentTypeFilter
     */
    protected function get08d2945e80d03d32cb8abe1dc615517acd686526a87c0afcc93a0fdf5204f355(): \Viserio\Component\Exception\Filter\ContentTypeFilter
    {
        return $this->services[\Viserio\Component\Exception\Filter\ContentTypeFilter::class] = new \Viserio\Component\Exception\Filter\ContentTypeFilter();
    }

    /**
     * Returns the public Viserio\Component\Exception\Filter\VerboseFilter shared service.
     *
     * @return \Viserio\Component\Exception\Filter\VerboseFilter
     */
    protected function get90d6500a6c35de72475ff2df52f6923ac58ae0eea0f173b0f931c854f41939fd(): \Viserio\Component\Exception\Filter\VerboseFilter
    {
        return $this->services[\Viserio\Component\Exception\Filter\VerboseFilter::class] = new \Viserio\Component\Exception\Filter\VerboseFilter(($this->services[\Viserio\Contract\Config\Repository::class] ?? $this->getdf1c31fe4ba52c5a58984206611ddc1ed0e532dc8d86e860064543054d395666()));
    }

    /**
     * Returns the public Viserio\Component\Log\LogManager shared service.
     *
     * @return \Viserio\Component\Log\LogManager
     */
    protected function getafab5c05bf2396b9796ebb692ff953a79f0a908d696ed0ac4d3e3657b06421c1(): \Viserio\Component\Log\LogManager
    {
        return $this->services[\Viserio\Component\Log\LogManager::class] = new \Viserio\Component\Log\LogManager(($this->services[\Viserio\Contract\Config\Repository::class] ?? $this->getdf1c31fe4ba52c5a58984206611ddc1ed0e532dc8d86e860064543054d395666()));
    }

    /**
     * Returns the public Viserio\Component\View\Engine\FileEngine shared service.
     *
     * @return \Viserio\Component\View\Engine\FileEngine
     */
    protected function get1a6c73ea96b910b7c8cc9eccb8a2efd9908e964162cfa207eeef703514994b04(): \Viserio\Component\View\Engine\FileEngine
    {
        return $this->services[\Viserio\Component\View\Engine\FileEngine::class] = new \Viserio\Component\View\Engine\FileEngine();
    }

    /**
     * Returns the public Viserio\Component\View\Engine\MarkdownEngine shared service.
     *
     * @return \Viserio\Component\View\Engine\MarkdownEngine
     */
    protected function get198642be4740f0701f2a66d050b91dc830dda7c7647fc3ed590cde395b592d96(): \Viserio\Component\View\Engine\MarkdownEngine
    {
        return $this->services[\Viserio\Component\View\Engine\MarkdownEngine::class] = new \Viserio\Component\View\Engine\MarkdownEngine(($this->services[Parsedown::class] ?? $this->get(Parsedown::class)));
    }

    /**
     * Returns the public Viserio\Component\View\Engine\PhpEngine shared service.
     *
     * @return \Viserio\Component\View\Engine\PhpEngine
     */
    protected function getd01d428260fd74997b150257850eb533cb546f9df452b1033a6c2fae22551a64(): \Viserio\Component\View\Engine\PhpEngine
    {
        return $this->services[\Viserio\Component\View\Engine\PhpEngine::class] = new \Viserio\Component\View\Engine\PhpEngine();
    }
}
