<?php

declare(strict_types=1);

/**
 * This file is part of Narrowspark Framework.
 *
 * (c) Daniel Bannert <d.bannert@anolilab.de>
 *
 * This source file is subject to the MIT license that is bundled
 * with this source code in the file LICENSE.
 */

namespace Container87cf0c2ab6a3a5d7053e59fc09878bbf23c39430e36ea06e35bd7179c880bbe9;

/**
 * This class has been auto-generated by Viserio Container Component.
 */
final class MailServiceProviderContainerTestProvider extends \Viserio\Component\Container\AbstractCompiledContainer
{
    /**
     * Path to the container dir.
     *
     * @var string
     */
    private $containerDir;

    /**
     * Create a new Compiled Container instance.
     *
     * @param array  $buildParameters
     * @param string $containerDir
     *
     * @var string $containerDir
     */
    public function __construct(array $buildParameters = [], string $containerDir = __DIR__)
    {
        $this->services = $this->privates = [];
        $this->containerDir = $containerDir;
        $this->parameters = \array_merge([
            'container.dumper.inline_factories' => true,
            'container.dumper.inline_class_loader' => false,
        ], $buildParameters);
        $this->methodMapping = [
            \Viserio\Contract\Events\EventManager::class => 'getd89597e6b0951303b9c81d9663646ce16e63e5d0cf7daeed45f04779b8a60c3b',
            \Viserio\Contract\Filesystem\Filesystem::class => 'get787a79c940e7519357cde00935d657a813a0ce7c7b555cf3cb98d8c2263d18c6',
            \Viserio\Contract\Mail\Mailer::class => 'getef189fbb8f6eb4ebb65e83bc190f2e81047e04731932155a69878da4168f4863',
            \Viserio\Contract\View\EngineResolver::class => 'getff73b374d52eb13f0773f58273de538d62944effed5c8e2a7caa31b6d2180e5b',
            \Viserio\Contract\View\Factory::class => 'getb6b69b8c40146f590f39a23a8d000f621d6288e79e53d4fdbeae0164b92c7d63',
            \Viserio\Contract\View\Finder::class => 'get2bc187b27da90a561b690d6fd54a3000d8276c6e5b8e8167ce59a4b9355b3859',
            \Viserio\Component\Mail\MailManager::class => 'get7e11fa86b2dc9b0e450d0336dd0f9adff1fb37319186b80ae6487ab7e30c9c32',
            \Viserio\Component\Mail\TransportFactory::class => 'get06d82cd796b1f9723eb7da581fb9a4e98c7ace8aa750d3da95b7e53cccea6a95',
            \Viserio\Component\View\Engine\FileEngine::class => 'get1a6c73ea96b910b7c8cc9eccb8a2efd9908e964162cfa207eeef703514994b04',
            \Viserio\Component\View\Engine\PhpEngine::class => 'getd01d428260fd74997b150257850eb533cb546f9df452b1033a6c2fae22551a64',
            'config' => 'get34bcaa5afa8745d92e6161e8495be3b939c5c6abb4dc2fd1f5a3cfdaba620256',
        ];
        $this->aliases = [
            \Viserio\Contract\Mail\QueueMailer::class => \Viserio\Contract\Mail\Mailer::class,
            \Viserio\Component\Events\EventManager::class => \Viserio\Contract\Events\EventManager::class,
            \Viserio\Component\Filesystem\Filesystem::class => \Viserio\Contract\Filesystem\Filesystem::class,
            \Viserio\Component\View\ViewFactory::class => \Viserio\Contract\View\Factory::class,
            \Viserio\Component\View\ViewFinder::class => \Viserio\Contract\View\Finder::class,
            'events' => \Viserio\Contract\Events\EventManager::class,
            'files' => \Viserio\Contract\Filesystem\Filesystem::class,
            'mailer' => \Viserio\Contract\Mail\Mailer::class,
            'view' => \Viserio\Contract\View\Factory::class,
            'view.engine.resolver' => \Viserio\Contract\View\EngineResolver::class,
            'view.finder' => \Viserio\Contract\View\Finder::class,
        ];
        $this->syntheticIds = [
            \Psr\Log\LoggerInterface::class => true,
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function getRemovedIds(): array
    {
        return require $this->containerDir . '/removed-ids.php';
    }

    /**
     * Returns the public Viserio\Contract\Events\EventManager shared service.
     *
     * @return \Viserio\Component\Events\EventManager
     */
    protected function getd89597e6b0951303b9c81d9663646ce16e63e5d0cf7daeed45f04779b8a60c3b(): \Viserio\Component\Events\EventManager
    {
        return $this->services[\Viserio\Contract\Events\EventManager::class] = new \Viserio\Component\Events\EventManager();
    }

    /**
     * Returns the public Viserio\Contract\Filesystem\Filesystem shared service.
     *
     * @return \Viserio\Component\Filesystem\Filesystem
     */
    protected function get787a79c940e7519357cde00935d657a813a0ce7c7b555cf3cb98d8c2263d18c6(): \Viserio\Component\Filesystem\Filesystem
    {
        return $this->services[\Viserio\Contract\Filesystem\Filesystem::class] = new \Viserio\Component\Filesystem\Filesystem();
    }

    /**
     * Returns the public Viserio\Contract\Mail\Mailer shared service.
     *
     * @return mixed An instance returned by \Viserio\Component\Container\Definition\ReferenceDefinition::getConnection()
     */
    protected function getef189fbb8f6eb4ebb65e83bc190f2e81047e04731932155a69878da4168f4863()
    {
        return $this->services[\Viserio\Contract\Mail\Mailer::class] = ($this->services[\Viserio\Component\Mail\MailManager::class] ?? $this->get7e11fa86b2dc9b0e450d0336dd0f9adff1fb37319186b80ae6487ab7e30c9c32())->getConnection();
    }

    /**
     * Returns the public Viserio\Contract\View\EngineResolver service.
     *
     * @return \Viserio\Component\View\Engine\IteratorViewEngineLoader
     */
    protected function getff73b374d52eb13f0773f58273de538d62944effed5c8e2a7caa31b6d2180e5b(): \Viserio\Component\View\Engine\IteratorViewEngineLoader
    {
        return new \Viserio\Component\View\Engine\IteratorViewEngineLoader(new \Viserio\Component\Container\RewindableGenerator(function () {
            yield 'file' => ($this->services[\Viserio\Component\View\Engine\FileEngine::class] ?? $this->get1a6c73ea96b910b7c8cc9eccb8a2efd9908e964162cfa207eeef703514994b04());

            yield 'php' => ($this->services[\Viserio\Component\View\Engine\PhpEngine::class] ?? $this->getd01d428260fd74997b150257850eb533cb546f9df452b1033a6c2fae22551a64());
        }, 2));
    }

    /**
     * Returns the public Viserio\Contract\View\Factory shared service.
     *
     * @return \Viserio\Component\View\ViewFactory
     */
    protected function getb6b69b8c40146f590f39a23a8d000f621d6288e79e53d4fdbeae0164b92c7d63(): \Viserio\Component\View\ViewFactory
    {
        $this->services[\Viserio\Contract\View\Factory::class] = $instance = new \Viserio\Component\View\ViewFactory(new \Viserio\Component\View\Engine\IteratorViewEngineLoader(new \Viserio\Component\Container\RewindableGenerator(function () {
            yield 'file' => ($this->services[\Viserio\Component\View\Engine\FileEngine::class] ?? $this->get1a6c73ea96b910b7c8cc9eccb8a2efd9908e964162cfa207eeef703514994b04());

            yield 'php' => ($this->services[\Viserio\Component\View\Engine\PhpEngine::class] ?? $this->getd01d428260fd74997b150257850eb533cb546f9df452b1033a6c2fae22551a64());
        }, 2)), ($this->services[\Viserio\Contract\View\Finder::class] ?? $this->get2bc187b27da90a561b690d6fd54a3000d8276c6e5b8e8167ce59a4b9355b3859()));

        $instance->share('app', $this);

        return $instance;
    }

    /**
     * Returns the public Viserio\Contract\View\Finder shared service.
     *
     * @return \Viserio\Component\View\ViewFinder
     */
    protected function get2bc187b27da90a561b690d6fd54a3000d8276c6e5b8e8167ce59a4b9355b3859(): \Viserio\Component\View\ViewFinder
    {
        return $this->services[\Viserio\Contract\View\Finder::class] = new \Viserio\Component\View\ViewFinder([
            'viserio' => [
                'mail' => [
                    'connections' => [],
                ],
                'view' => [
                    'paths' => [
                        0 => '/var/www/framework/src/Viserio/Component/Mail/Tests/Container/Provider',
                    ],
                    'extensions' => [
                        0 => 'php',
                    ],
                ],
            ],
        ]);
    }

    /**
     * Returns the public Viserio\Component\Mail\MailManager shared service.
     *
     * @return \Viserio\Component\Mail\MailManager
     */
    protected function get7e11fa86b2dc9b0e450d0336dd0f9adff1fb37319186b80ae6487ab7e30c9c32(): \Viserio\Component\Mail\MailManager
    {
        $this->services[\Viserio\Component\Mail\MailManager::class] = $instance = new \Viserio\Component\Mail\MailManager([
            'viserio' => [
                'mail' => [
                    'connections' => [],
                ],
                'view' => [
                    'paths' => [
                        0 => '/var/www/framework/src/Viserio/Component/Mail/Tests/Container/Provider',
                    ],
                    'extensions' => [
                        0 => 'php',
                    ],
                ],
            ],
        ], ($this->services[\Viserio\Component\Mail\TransportFactory::class] ?? $this->get06d82cd796b1f9723eb7da581fb9a4e98c7ace8aa750d3da95b7e53cccea6a95()));

        $instance->setContainer($this);

        if (isset($this->services[\Viserio\Contract\View\Factory::class])) {
            $instance->setViewFactory(($this->services[\Viserio\Contract\View\Factory::class] ?? null));
        }

        if (isset($this->services[\Viserio\Contract\Events\EventManager::class])) {
            $instance->setEventManager(($this->services[\Viserio\Contract\Events\EventManager::class] ?? null));
        }

        return $instance;
    }

    /**
     * Returns the public Viserio\Component\Mail\TransportFactory shared service.
     *
     * @return \Viserio\Component\Mail\TransportFactory
     */
    protected function get06d82cd796b1f9723eb7da581fb9a4e98c7ace8aa750d3da95b7e53cccea6a95(): \Viserio\Component\Mail\TransportFactory
    {
        $this->services[\Viserio\Component\Mail\TransportFactory::class] = $instance = new \Viserio\Component\Mail\TransportFactory();

        $instance->setLogger(($this->services[\Psr\Log\LoggerInterface::class] ?? $this->get(\Psr\Log\LoggerInterface::class)));

        return $instance;
    }

    /**
     * Returns the public Viserio\Component\View\Engine\FileEngine shared service.
     *
     * @return \Viserio\Component\View\Engine\FileEngine
     */
    protected function get1a6c73ea96b910b7c8cc9eccb8a2efd9908e964162cfa207eeef703514994b04(): \Viserio\Component\View\Engine\FileEngine
    {
        return $this->services[\Viserio\Component\View\Engine\FileEngine::class] = new \Viserio\Component\View\Engine\FileEngine();
    }

    /**
     * Returns the public Viserio\Component\View\Engine\PhpEngine shared service.
     *
     * @return \Viserio\Component\View\Engine\PhpEngine
     */
    protected function getd01d428260fd74997b150257850eb533cb546f9df452b1033a6c2fae22551a64(): \Viserio\Component\View\Engine\PhpEngine
    {
        return $this->services[\Viserio\Component\View\Engine\PhpEngine::class] = new \Viserio\Component\View\Engine\PhpEngine();
    }

    /**
     * Returns the public config service.
     *
     * @return array
     */
    protected function get34bcaa5afa8745d92e6161e8495be3b939c5c6abb4dc2fd1f5a3cfdaba620256(): array
    {
        return [
            'viserio' => [
                'mail' => [
                    'connections' => [],
                ],
                'view' => [
                    'paths' => [
                        0 => '/var/www/framework/src/Viserio/Component/Mail/Tests/Container/Provider',
                    ],
                    'extensions' => [
                        0 => 'php',
                    ],
                ],
            ],
        ];
    }
}
