<?php

declare(strict_types=1);

namespace Viserio\Component\View\Tests\Provider\Compiled;

/**
 * This class has been auto-generated by Viserio Container Component.
 */
final class ViewServiceProviderContainer extends \Viserio\Component\Container\AbstractCompiledContainer
{
    /**
     * Create a new Compiled Container instance.
     */
    public function __construct()
    {
        $this->services = $this->privates = [];
        $this->parameters = [
            'viserio' => [
                'view' => [
                    'paths' => [
                        0 => '/var/www/framework/src/Viserio/Component/View/Tests/Container/Fixture/',
                        1 => '/var/www/framework/src/Viserio/Component/View/Tests/Container/Provider',
                    ],
                    'extensions' => [
                        0 => 'phtml',
                        1 => 'php',
                    ],
                ],
            ],
        ];
        $this->methodMapping = [
            \Viserio\Component\Config\Command\ConfigDumpCommand::class => 'get88001f5d55ce57598db2e5b80611a49d605be7b037e634e18ca2493683a114ee',
            \Viserio\Component\Config\Command\ConfigReaderCommand::class => 'get91fd613885c83bb4b00b29ee3e879446444b7ecad7fdd0292ef1df30bdfa3884',
            \Viserio\Component\View\Engine\FileEngine::class => 'get1a6c73ea96b910b7c8cc9eccb8a2efd9908e964162cfa207eeef703514994b04',
            \Viserio\Component\View\Engine\PhpEngine::class => 'getd01d428260fd74997b150257850eb533cb546f9df452b1033a6c2fae22551a64',
            \Viserio\Contract\View\EngineResolver::class => 'get2016373b7f5c73f0ef51fb001fb92130aa9f0c0365ed5432165d735d28532db2',
            \Viserio\Contract\View\Factory::class => 'getc1da5fd35274b671a8fddde5be07d5ee91b0f0017e4c361e39760bf129bb6f1e',
            \Viserio\Contract\View\Finder::class => 'gete49bc19aea9de0a9a35cb4f48103a3a278f1a6ea142aacd4ae71132b55034f49',
        ];
        $this->aliases = [
            \Viserio\Component\View\ViewFactory::class => \Viserio\Contract\View\Factory::class,
            \Viserio\Component\View\ViewFinder::class => \Viserio\Contract\View\Finder::class,
            'view' => \Viserio\Contract\View\Factory::class,
            'view.engine.resolver' => \Viserio\Contract\View\EngineResolver::class,
            'view.finder' => \Viserio\Contract\View\Finder::class,
        ];
    }

    /**
     * Returns the public Viserio\Component\Config\Command\ConfigDumpCommand shared service.
     *
     * @return \Viserio\Component\Config\Command\ConfigDumpCommand
     */
    protected function get88001f5d55ce57598db2e5b80611a49d605be7b037e634e18ca2493683a114ee(): \Viserio\Component\Config\Command\ConfigDumpCommand
    {
        return $this->services[\Viserio\Component\Config\Command\ConfigDumpCommand::class] = new \Viserio\Component\Config\Command\ConfigDumpCommand();
    }

    /**
     * Returns the public Viserio\Component\Config\Command\ConfigReaderCommand shared service.
     *
     * @return \Viserio\Component\Config\Command\ConfigReaderCommand
     */
    protected function get91fd613885c83bb4b00b29ee3e879446444b7ecad7fdd0292ef1df30bdfa3884(): \Viserio\Component\Config\Command\ConfigReaderCommand
    {
        return $this->services[\Viserio\Component\Config\Command\ConfigReaderCommand::class] = new \Viserio\Component\Config\Command\ConfigReaderCommand();
    }

    /**
     * Returns the public Viserio\Component\View\Engine\FileEngine shared service.
     *
     * @return \Viserio\Component\View\Engine\FileEngine
     */
    protected function get1a6c73ea96b910b7c8cc9eccb8a2efd9908e964162cfa207eeef703514994b04(): \Viserio\Component\View\Engine\FileEngine
    {
        return $this->services[\Viserio\Component\View\Engine\FileEngine::class] = new \Viserio\Component\View\Engine\FileEngine();
    }

    /**
     * Returns the public Viserio\Component\View\Engine\PhpEngine shared service.
     *
     * @return \Viserio\Component\View\Engine\PhpEngine
     */
    protected function getd01d428260fd74997b150257850eb533cb546f9df452b1033a6c2fae22551a64(): \Viserio\Component\View\Engine\PhpEngine
    {
        return $this->services[\Viserio\Component\View\Engine\PhpEngine::class] = new \Viserio\Component\View\Engine\PhpEngine();
    }

    /**
     * Returns the public Viserio\Contract\View\EngineResolver service.
     *
     * @return \Viserio\Component\View\Engine\IteratorViewEngineLoader
     */
    protected function get2016373b7f5c73f0ef51fb001fb92130aa9f0c0365ed5432165d735d28532db2(): \Viserio\Component\View\Engine\IteratorViewEngineLoader
    {
        return new \Viserio\Component\View\Engine\IteratorViewEngineLoader(new \Viserio\Component\Container\RewindableGenerator(function () {
            yield 'file' => ($this->services[\Viserio\Component\View\Engine\FileEngine::class] ?? $this->get1a6c73ea96b910b7c8cc9eccb8a2efd9908e964162cfa207eeef703514994b04());
            yield 'php' => ($this->services[\Viserio\Component\View\Engine\PhpEngine::class] ?? $this->getd01d428260fd74997b150257850eb533cb546f9df452b1033a6c2fae22551a64());
        }, 2));
    }

    /**
     * Returns the public Viserio\Contract\View\Factory shared service.
     *
     * @return \Viserio\Component\View\ViewFactory
     */
    protected function getc1da5fd35274b671a8fddde5be07d5ee91b0f0017e4c361e39760bf129bb6f1e(): \Viserio\Component\View\ViewFactory
    {
        $this->services[\Viserio\Contract\View\Factory::class] = $instance = new \Viserio\Component\View\ViewFactory(new \Viserio\Component\View\Engine\IteratorViewEngineLoader(new \Viserio\Component\Container\RewindableGenerator(function () {
            yield 'file' => ($this->services[\Viserio\Component\View\Engine\FileEngine::class] ?? $this->get1a6c73ea96b910b7c8cc9eccb8a2efd9908e964162cfa207eeef703514994b04());
            yield 'php' => ($this->services[\Viserio\Component\View\Engine\PhpEngine::class] ?? $this->getd01d428260fd74997b150257850eb533cb546f9df452b1033a6c2fae22551a64());
        }, 2)), ($this->services[\Viserio\Contract\View\Finder::class] ?? $this->gete49bc19aea9de0a9a35cb4f48103a3a278f1a6ea142aacd4ae71132b55034f49()));

        $instance->share('app', $this);

        return $instance;
    }

    /**
     * Returns the public Viserio\Contract\View\Finder shared service.
     *
     * @return \Viserio\Component\View\ViewFinder
     */
    protected function gete49bc19aea9de0a9a35cb4f48103a3a278f1a6ea142aacd4ae71132b55034f49(): \Viserio\Component\View\ViewFinder
    {
        return $this->services[\Viserio\Contract\View\Finder::class] = new \Viserio\Component\View\ViewFinder($this->getParameter('viserio.view.paths'), []);
    }

    /**
     * {@inheritdoc}
     */
    public function getRemovedIds(): array
    {
        return [
            \Psr\Container\ContainerInterface::class => true,
            \Viserio\Contract\Container\CompiledContainer::class => true,
            \Viserio\Contract\Container\Factory::class => true,
            \Viserio\Contract\Container\TaggedContainer::class => true,
            'container' => true,
        ];
    }
}
