<?php

declare(strict_types=1);

namespace Viserio\Component\Container\Tests\IntegrationTest\Compiled;

/**
 * This class has been auto-generated by Viserio Container Component.
 */
final class ContainerDelegateContainerTestAliasToDependencyInDelegateContainer extends \Viserio\Component\Container\AbstractCompiledContainer
{
    /**
     * Create a new Compiled Container instance.
     */
    public function __construct()
    {
        $this->services = $this->privates = [];
        $this->methodMapping = [
            'instance2' => 'gete55ff34ba81526dc81e5e4410c486adf6a3455c49ed6ce20ff5df44600f9e8ab',
        ];
    }

    /**
     * Returns the public instance2 service.
     *
     * @return \stdClass
     */
    protected function gete55ff34ba81526dc81e5e4410c486adf6a3455c49ed6ce20ff5df44600f9e8ab(): \stdClass
    {
        $instance = new \stdClass();

        $instance->ff = ($this->services['instance'] ?? $this->get('instance'));

        return $instance;
    }

    /**
     * {@inheritdoc}
     */
    public function getRemovedIds(): array
    {
        return [
            \Psr\Container\ContainerInterface::class => true,
            \Viserio\Contract\Container\Factory::class => true,
            \Viserio\Contract\Container\TaggedContainer::class => true,
            'container' => true,
        ];
    }
}
