<?php

declare(strict_types=1);

namespace Viserio\Component\Container\Tests\IntegrationTest\Compiled;

/**
 * This class has been auto-generated by Viserio Container Component.
 */
final class ContainerLazyObjectContainerTestGenerateOneLazyProxyForSameClass extends \Viserio\Component\Container\AbstractCompiledContainer
{
    /**
     * Create a new Compiled Container instance.
     */
    public function __construct()
    {
        $this->services = $this->privates = [];
        $this->methodMapping = [
            'bar' => 'get91b123d3875702532e36683116824223d37b37377003156fc244abb2a82fec9c',
            'foo' => 'get55df4251026261c15e5362b72748729c5413605491a6b31caf07b0571c04af5f',
        ];
    }

    /**
     * Returns the public bar service.
     *
     * @return \stdClass
     */
    protected function get91b123d3875702532e36683116824223d37b37377003156fc244abb2a82fec9c(): \stdClass
    {
        return $this->createProxy('stdClass_7505e02fc61bdbec8ef82430242d0041c28f8477d8fc1e70135fd3b6d304a641', static function () {
            return stdClass_7505e02fc61bdbec8ef82430242d0041c28f8477d8fc1e70135fd3b6d304a641::staticProxyConstructor(static function (&$wrappedInstance, \ProxyManager\Proxy\LazyLoadingInterface $proxy) {
                $wrappedInstance = new \stdClass();
                $proxy->setProxyInitializer(null);

                return true;
            });
        });
    }

    /**
     * Returns the public foo service.
     *
     * @return \stdClass
     */
    protected function get55df4251026261c15e5362b72748729c5413605491a6b31caf07b0571c04af5f(): \stdClass
    {
        return $this->createProxy('stdClass_7505e02fc61bdbec8ef82430242d0041c28f8477d8fc1e70135fd3b6d304a641', static function () {
            return stdClass_7505e02fc61bdbec8ef82430242d0041c28f8477d8fc1e70135fd3b6d304a641::staticProxyConstructor(static function (&$wrappedInstance, \ProxyManager\Proxy\LazyLoadingInterface $proxy) {
                $wrappedInstance = new \stdClass();
                $proxy->setProxyInitializer(null);

                return true;
            });
        });
    }

    /**
     * {@inheritdoc}
     */
    public function getRemovedIds(): array
    {
        return [
            \Psr\Container\ContainerInterface::class => true,
            \Viserio\Contract\Container\Factory::class => true,
            \Viserio\Contract\Container\TaggedContainer::class => true,
            'container' => true,
        ];
    }

    /**
     * Invoke a proxy instance.
     *
     * @param string   $class
     * @param \Closure $factory
     *
     * @return object
     */
    protected function createProxy(string $class, \Closure $factory): object
    {
        \class_exists($class, false) || \class_alias("Viserio\Component\Container\Tests\IntegrationTest\Compiled\\{$class}", $class, false);

        return $factory();
    }
}

class stdClass_7505e02fc61bdbec8ef82430242d0041c28f8477d8fc1e70135fd3b6d304a641 extends \stdClass implements \ProxyManager\Proxy\VirtualProxyInterface
{
    private $valueHolder24eaa = null;
    private $initializer8c62e = null;
    private static $publicProperties9f138 = [

    ];
    public static function staticProxyConstructor($initializer)
    {
        static $reflection;
        $reflection = $reflection ?? new \ReflectionClass(__CLASS__);
        $instance = $reflection->newInstanceWithoutConstructor();
        $instance->initializer8c62e = $initializer;
        return $instance;
    }
    public function __construct()
    {
        static $reflection;
        if (! $this->valueHolder24eaa) {
            $reflection = $reflection ?? new \ReflectionClass('stdClass');
            $this->valueHolder24eaa = $reflection->newInstanceWithoutConstructor();
        }
    }
    public function & __get($name)
    {
        $this->initializer8c62e && ($this->initializer8c62e->__invoke($valueHolder24eaa, $this, '__get', ['name' => $name], $this->initializer8c62e) || 1) && $this->valueHolder24eaa = $valueHolder24eaa;
        if (isset(self::$publicProperties9f138[$name])) {
            return $this->valueHolder24eaa->$name;
        }
        $realInstanceReflection = new \ReflectionClass(get_parent_class($this));
        if (! $realInstanceReflection->hasProperty($name)) {
            $targetObject = $this->valueHolder24eaa;
            $backtrace = debug_backtrace(false);
            trigger_error(
                sprintf(
                    'Undefined property: %s::$%s in %s on line %s',
                    get_parent_class($this),
                    $name,
                    $backtrace[0]['file'],
                    $backtrace[0]['line']
                ),
                \E_USER_NOTICE
            );
            return $targetObject->$name;
            return;
        }
        $targetObject = $this->valueHolder24eaa;
        $accessor = function & () use ($targetObject, $name) {
            return $targetObject->$name;
        };
        $backtrace = debug_backtrace(true);
        $scopeObject = isset($backtrace[1]['object']) ? $backtrace[1]['object'] : new \ProxyManager\Stub\EmptyClassStub();
        $accessor = $accessor->bindTo($scopeObject, get_class($scopeObject));
        $returnValue = & $accessor();
        return $returnValue;
    }
    public function __set($name, $value)
    {
        $this->initializer8c62e && ($this->initializer8c62e->__invoke($valueHolder24eaa, $this, '__set', array('name' => $name, 'value' => $value), $this->initializer8c62e) || 1) && $this->valueHolder24eaa = $valueHolder24eaa;
        $realInstanceReflection = new \ReflectionClass(get_parent_class($this));
        if (! $realInstanceReflection->hasProperty($name)) {
            $targetObject = $this->valueHolder24eaa;
            return $targetObject->$name = $value;
            return;
        }
        $targetObject = $this->valueHolder24eaa;
        $accessor = function & () use ($targetObject, $name, $value) {
            return $targetObject->$name = $value;
        };
        $backtrace = debug_backtrace(true);
        $scopeObject = isset($backtrace[1]['object']) ? $backtrace[1]['object'] : new \ProxyManager\Stub\EmptyClassStub();
        $accessor = $accessor->bindTo($scopeObject, get_class($scopeObject));
        $returnValue = & $accessor();
        return $returnValue;
    }
    public function __isset($name)
    {
        $this->initializer8c62e && ($this->initializer8c62e->__invoke($valueHolder24eaa, $this, '__isset', array('name' => $name), $this->initializer8c62e) || 1) && $this->valueHolder24eaa = $valueHolder24eaa;
        $realInstanceReflection = new \ReflectionClass(get_parent_class($this));
        if (! $realInstanceReflection->hasProperty($name)) {
            $targetObject = $this->valueHolder24eaa;
            return isset($targetObject->$name);
            return;
        }
        $targetObject = $this->valueHolder24eaa;
        $accessor = function () use ($targetObject, $name) {
            return isset($targetObject->$name);
        };
        $backtrace = debug_backtrace(true);
        $scopeObject = isset($backtrace[1]['object']) ? $backtrace[1]['object'] : new \ProxyManager\Stub\EmptyClassStub();
        $accessor = $accessor->bindTo($scopeObject, get_class($scopeObject));
        $returnValue = $accessor();
        return $returnValue;
    }
    public function __unset($name)
    {
        $this->initializer8c62e && ($this->initializer8c62e->__invoke($valueHolder24eaa, $this, '__unset', array('name' => $name), $this->initializer8c62e) || 1) && $this->valueHolder24eaa = $valueHolder24eaa;
        $realInstanceReflection = new \ReflectionClass(get_parent_class($this));
        if (! $realInstanceReflection->hasProperty($name)) {
            $targetObject = $this->valueHolder24eaa;
            unset($targetObject->$name);
            return;
        }
        $targetObject = $this->valueHolder24eaa;
        $accessor = function () use ($targetObject, $name) {
            unset($targetObject->$name);
        };
        $backtrace = debug_backtrace(true);
        $scopeObject = isset($backtrace[1]['object']) ? $backtrace[1]['object'] : new \ProxyManager\Stub\EmptyClassStub();
        $accessor = $accessor->bindTo($scopeObject, get_class($scopeObject));
        $returnValue = $accessor();
        return $returnValue;
    }
    public function __clone()
    {
        $this->initializer8c62e && ($this->initializer8c62e->__invoke($valueHolder24eaa, $this, '__clone', array(), $this->initializer8c62e) || 1) && $this->valueHolder24eaa = $valueHolder24eaa;
        $this->valueHolder24eaa = clone $this->valueHolder24eaa;
    }
    public function __sleep()
    {
        $this->initializer8c62e && ($this->initializer8c62e->__invoke($valueHolder24eaa, $this, '__sleep', array(), $this->initializer8c62e) || 1) && $this->valueHolder24eaa = $valueHolder24eaa;
        return array('valueHolder24eaa');
    }
    public function __wakeup()
    {
    }
    public function setProxyInitializer(\Closure $initializer = null)
    {
        $this->initializer8c62e = $initializer;
    }
    public function getProxyInitializer()
    {
        return $this->initializer8c62e;
    }
    public function initializeProxy() : bool
    {
        return $this->initializer8c62e && ($this->initializer8c62e->__invoke($valueHolder24eaa, $this, 'initializeProxy', array(), $this->initializer8c62e) || 1) && $this->valueHolder24eaa = $valueHolder24eaa;
    }
    public function isProxyInitialized() : bool
    {
        return null !== $this->valueHolder24eaa;
    }
    public function getWrappedValueHolderValue() : ?object
    {
        return $this->valueHolder24eaa;
    }
}
