<?php

declare(strict_types=1);

namespace Viserio\Component\Container\Tests\IntegrationTest\Compiled;

/**
 * This class has been auto-generated by Viserio Container Component.
 */
final class ContainerServiceProviderContainerTestContainerCanBeDumpedWithRegisteredProviderServices extends \Viserio\Component\Container\AbstractCompiledContainer
{
    /**
     * Create a new Compiled Container instance.
     */
    public function __construct()
    {
        $this->services = $this->privates = [];
        $this->parameters = [
            'param' => 'value',
        ];
        $this->methodMapping = [
            'service' => 'get361043af246e7c8166dac3d9521cd38ed69a8d2f9075493f181c581560d7b289',
        ];
    }

    /**
     * Returns the public service shared service.
     *
     * @return \Viserio\Component\Container\Tests\Fixture\ServiceProvider\ServiceFixture
     */
    protected function get361043af246e7c8166dac3d9521cd38ed69a8d2f9075493f181c581560d7b289(): \Viserio\Component\Container\Tests\Fixture\ServiceProvider\ServiceFixture
    {
        return $this->services['service'] = new \Viserio\Component\Container\Tests\Fixture\ServiceProvider\ServiceFixture();
    }

    /**
     * {@inheritdoc}
     */
    public function getRemovedIds(): array
    {
        return [
            \Psr\Container\ContainerInterface::class => true,
            \Viserio\Contract\Container\Factory::class => true,
            \Viserio\Contract\Container\TaggedContainer::class => true,
            'container' => true,
        ];
    }
}
