<?php

declare(strict_types=1);

namespace Viserio\Component\Container\Tests\IntegrationTest\Dumper\Compiled;

/**
 * This class has been auto-generated by Viserio Container Component.
 */
final class PhpDumperContainerTestInlineSelfRef extends \Viserio\Component\Container\AbstractCompiledContainer
{
    /**
     * Create a new Compiled Container instance.
     */
    public function __construct()
    {
        $this->services = $this->privates = [];
        $this->methodMapping = [
            'App\\Foo' => 'get1b7a5b637a56c0fd6aed5e969629135ca33ba8f644584cd2dcd227a63b14c629',
        ];
    }

    /**
     * Returns the public App\Foo shared service.
     *
     * @return \stdClass
     */
    protected function get1b7a5b637a56c0fd6aed5e969629135ca33ba8f644584cd2dcd227a63b14c629(): \stdClass
    {
        $a = new \stdClass();

        $b = new \stdClass($a);
        $b->bar = $a;

        $this->services['App\\Foo'] = $instance = new \stdClass($b);

        $a->foo = $instance;

        return $instance;
    }

    /**
     * {@inheritdoc}
     */
    public function getRemovedIds(): array
    {
        return [
            \Psr\Container\ContainerInterface::class => true,
            \Viserio\Contract\Container\Factory::class => true,
            \Viserio\Contract\Container\TaggedContainer::class => true,
            'container' => true,
        ];
    }
}
