<?php

declare(strict_types=1);

namespace Viserio\Component\Container\Tests\Integration\Dumper\Compiled;

/**
 * This class has been auto-generated by Viserio Container Component.
 */
final class PhpDumperContainerTestContainerCanBeDumpedWithIteratorAndBindServices extends \Viserio\Component\Container\AbstractCompiledContainer
{
    /**
     * Create a new Compiled Container instance.
     */
    public function __construct()
    {
        $this->services = $this->privates = [];
        $this->methodMapping = [
            'iterator' => 'get46e68a7e5da8ca83e667471651fd83ead86636329ad944641912155ca224ed25',
        ];
    }

    /**
     * Returns the public iterator shared service.
     *
     * @return \Viserio\Component\Container\RewindableGenerator
     */
    protected function get46e68a7e5da8ca83e667471651fd83ead86636329ad944641912155ca224ed25(): \Viserio\Component\Container\RewindableGenerator
    {
        return $this->services['iterator'] = new \Viserio\Component\Container\RewindableGenerator(function () {
            yield 0 => ($this->privates['FooClassWithMethodCall'] ?? $this->get112d3232eac85c1ece2db4c45307491df56f32c1cdaa742410b68dd224934b2b());
            yield 1 => ($this->privates[\stdClass::class] ?? $this->get7505e02fc61bdbec8ef82430242d0041c28f8477d8fc1e70135fd3b6d304a641());
            yield 2 => $this->get601ebbf111eade1dea92676086466647f1ade8dccb6090fb680c0566ce14bea4();
        }, 3);
    }

    /**
     * Returns the private FooClassWithMethodCall shared service.
     *
     * @return \Viserio\Component\Container\Tests\Fixture\FooClass
     */
    protected function get112d3232eac85c1ece2db4c45307491df56f32c1cdaa742410b68dd224934b2b(): \Viserio\Component\Container\Tests\Fixture\FooClass
    {
        $this->privates['FooClassWithMethodCall'] = $instance = new \Viserio\Component\Container\Tests\Fixture\FooClass();

        $instance->setBar('55');

        return $instance;
    }

    /**
     * Returns the private baz service.
     *
     * @return \stdClass
     */
    protected function get601ebbf111eade1dea92676086466647f1ade8dccb6090fb680c0566ce14bea4(): \stdClass
    {
        return new \stdClass();
    }

    /**
     * Returns the private stdClass shared service.
     *
     * @return \stdClass
     */
    protected function get7505e02fc61bdbec8ef82430242d0041c28f8477d8fc1e70135fd3b6d304a641(): \stdClass
    {
        return $this->privates[\stdClass::class] = new \stdClass();
    }

    /**
     * {@inheritdoc}
     */
    public function getRemovedIds(): array
    {
        return [
            'FooClassWithMethodCall' => true,
            \Psr\Container\ContainerInterface::class => true,
            \Viserio\Contract\Container\CompiledContainer::class => true,
            \Viserio\Contract\Container\Factory::class => true,
            \Viserio\Contract\Container\TaggedContainer::class => true,
            'baz' => true,
            'container' => true,
            \stdClass::class => true,
        ];
    }
}
