<?php

declare(strict_types=1);

namespace Viserio\Component\Container\Tests\Integration\Dumper\Compiled;

/**
 * This class has been auto-generated by Viserio Container Component.
 */
final class PhpDumperContainerTestContainerCanBeDumpedWithIgnoreOnInvalidReference extends \Viserio\Component\Container\AbstractCompiledContainer
{
    /**
     * Create a new Compiled Container instance.
     */
    public function __construct()
    {
        $this->services = $this->privates = [];
        $this->methodMapping = [
            'maaa' => 'get2a3ccff57e799eaca81502a9a862eccdd07c950486d7445cf7ab6a77317e6d6d',
        ];
    }

    /**
     * Returns the public maaa service.
     *
     * @return \Viserio\Component\Container\Tests\Fixture\FactoryClass
     */
    protected function get2a3ccff57e799eaca81502a9a862eccdd07c950486d7445cf7ab6a77317e6d6d(): \Viserio\Component\Container\Tests\Fixture\FactoryClass
    {
        return new \Viserio\Component\Container\Tests\Fixture\FactoryClass();
    }

    /**
     * {@inheritdoc}
     */
    public function getRemovedIds(): array
    {
        return [
            \Psr\Container\ContainerInterface::class => true,
            \Viserio\Component\Container\Tests\Fixture\Autowire\CollisionInterface::class => true,
            \Viserio\Contract\Container\CompiledContainer::class => true,
            \Viserio\Contract\Container\Factory::class => true,
            \Viserio\Contract\Container\TaggedContainer::class => true,
            'container' => true,
        ];
    }
}
