<?php

declare(strict_types=1);

namespace Viserio\Component\Container\Tests\Integration\Dumper\Compiled;

/**
 * This class has been auto-generated by Viserio Container Component.
 */
final class PhpDumperContainerTestContainerCanBeDumpedWithUseClassInCallable extends \Viserio\Component\Container\AbstractCompiledContainer
{
    /**
     * Create a new Compiled Container instance.
     */
    public function __construct()
    {
        $this->services = $this->privates = [];
        $this->methodMapping = [
            'be' => 'gete34e4d16116d12eadb070b397f80cedd86a0a1ebe0a947b84cd46b7cc55b5793',
        ];
    }

    /**
     * Returns the public be service.
     *
     * @return mixed Returned by a function
     */
    protected function gete34e4d16116d12eadb070b397f80cedd86a0a1ebe0a947b84cd46b7cc55b5793()
    {
        return (static function () {
    return new \Viserio\Component\Container\Tests\Fixture\FactoryClass();
})();
    }

    /**
     * {@inheritdoc}
     */
    public function getRemovedIds(): array
    {
        return [
            \Psr\Container\ContainerInterface::class => true,
            \Viserio\Contract\Container\CompiledContainer::class => true,
            \Viserio\Contract\Container\Factory::class => true,
            \Viserio\Contract\Container\TaggedContainer::class => true,
            'container' => true,
        ];
    }
}
