<?php

declare(strict_types=1);

namespace Viserio\Component\Container\Tests\IntegrationTest\Dumper\Compiled;

/**
 * This class has been auto-generated by Viserio Container Component.
 */
final class PhpDumperContainerTestDynamicParameterProcessor extends \Viserio\Component\Container\AbstractCompiledContainer
{
    /**
    * The stack of concretions currently being built.
    *
     * @var array<string, bool>
     */
    private $resolvingDynamicParameters = [];

    /**
     * Create a new Compiled Container instance.
     */
    public function __construct()
    {
        $this->services = $this->privates = [];
        $this->parameters = [
            'bar' => 'Bar',
            'container.parameter.provided.processor.types' => [
                'foo' => [
                    0 => 'string',
                ],
                'resolve' => [
                    0 => 'string',
                ],
                'bool' => [
                    0 => 'bool',
                ],
                'float' => [
                    0 => 'float',
                ],
                'int' => [
                    0 => 'int',
                ],
                'string' => [
                    0 => 'string',
                ],
                'trim' => [
                    0 => 'string',
                ],
                'json' => [
                    0 => 'array',
                ],
                'json_decode' => [
                    0 => 'array',
                ],
                'base64' => [
                    0 => 'string',
                ],
                'base64_decode' => [
                    0 => 'string',
                ],
                'env' => [
                    0 => 'string',
                ],
            ],
        ];
        $this->loadedDynamicParameters = [
            'foo' => false,
            'baz' => false,
            'foo2' => false,
            'json' => false,
        ];
        $this->methodMapping = [
            'container.parameter.processors' => 'get86047e9365daae20dafc971762ab81fee5d3d066aaa510eba312ea659095239b',
        ];
    }

    /**
     * Returns the public container.parameter.processors shared service.
     *
     * @return \Viserio\Component\Container\RewindableGenerator
     */
    protected function get86047e9365daae20dafc971762ab81fee5d3d066aaa510eba312ea659095239b(): \Viserio\Component\Container\RewindableGenerator
    {
        return $this->services['container.parameter.processors'] = new \Viserio\Component\Container\RewindableGenerator(function () {
            yield 0 => new \Viserio\Component\Container\Tests\Fixture\Processor\FooParameterProcessor();
            yield 1 => new \Viserio\Component\Container\Processor\ResolveParameterProcessor($this);
            yield 2 => new \Viserio\Component\Config\Processor\PhpTypeParameterProcessor();
            yield 3 => new \Viserio\Component\Config\Processor\JsonParameterProcessor();
            yield 4 => new \Viserio\Component\Config\Processor\Base64ParameterProcessor();
            yield 5 => new \Viserio\Component\Container\Tests\Fixture\Processor\EnvParameterProcessor();
        }, 6);
    }

    /**
     * {@inheritdoc}
     */
    public function getRemovedIds(): array
    {
        return [
            \Psr\Container\ContainerInterface::class => true,
            \Viserio\Component\Config\Processor\Base64ParameterProcessor::class => true,
            \Viserio\Component\Config\Processor\JsonParameterProcessor::class => true,
            \Viserio\Component\Config\Processor\PhpTypeParameterProcessor::class => true,
            \Viserio\Component\Container\Processor\ResolveParameterProcessor::class => true,
            \Viserio\Component\Container\Tests\Fixture\Processor\EnvParameterProcessor::class => true,
            \Viserio\Component\Container\Tests\Fixture\Processor\FooParameterProcessor::class => true,
            \Viserio\Contract\Container\CompiledContainer::class => true,
            \Viserio\Contract\Container\Factory::class => true,
            \Viserio\Contract\Container\TaggedContainer::class => true,
            'container' => true,
        ];
    }

    /**
     * {@inheritdoc}
     */
    protected function doGetParameter(string $id)
    {
        $process = function($value) {
            if (is_array($value)) {
                \array_walk_recursive($value, function (&$parameter): void {
                    $parameter = $this->processParameter($parameter);
                });

                return $value;
            }

            return $this->processParameter($value);
        };

        switch ($id) {
            case 'foo': $value = $process('Foo{DUMMY_BAR|env|resolve}'); break;
            case 'baz': $value = $process('{DUMMY_FOO|env|resolve}'); break;
            case 'foo2': $value = $process('{baz|foo}'); break;
            case 'json': $value = $process('{W10=|base64_decode|json_decode}'); break;

            default: return parent::doGetParameter($id);
        }

        $this->loadedDynamicParameters[$id] = true;

        return $this->dynamicParameters[$id] = $value;
    }

    /**
     * Process through value.
     *
     * @param int|string|float|bool $parameter
     *
     * @return int|string|float|bool
     */
    private function processParameter($parameter)
    {
        if (\is_string($parameter)) {
            \preg_match('/(.*)?\{(.+)\|(.*)\}/U', $parameter, $matches);

            $parameter = \array_reduce(\explode('|', $matches[3]), function ($carry, string $method) use ($parameter) {
                if ($carry === null) {
                    return;
                }

                $value = "{$carry}|{$method}";

                if (\array_key_exists($value, $this->resolvingDynamicParameters)) {
                    throw new \Viserio\Contract\Container\Exception\CircularParameterException($parameter, \array_keys($this->resolvingDynamicParameters));
                }

                /** @var \Viserio\Contract\Container\Processor\ParameterProcessor $processor */
                foreach ($this->get('container.parameter.processors') as $processor) {
                    if ($processor->supports($value)) {
                        $this->resolvingDynamicParameters[$value] = true;

                        return $processor->process($value);
                    }
                }
            }, $matches[2]);

            if (isset($matches[1]) && $matches[1] !== '') {
                $parameter = $matches[1].$parameter;
            }

            $this->resolvingDynamicParameters = [];
        }

        return $parameter;
    }
}
