<?php

declare(strict_types=1);

namespace Viserio\Component\Container\Tests\Integration\Dumper\Compiled;

/**
 * This class has been auto-generated by Viserio Container Component.
 */
final class PhpDumperContainerTestContainerCanBeDumpedWithMethodCallsInReferenceDefinition extends \Viserio\Component\Container\AbstractCompiledContainer
{
    /**
     * Create a new Compiled Container instance.
     */
    public function __construct()
    {
        $this->services = $this->privates = [];
        $this->methodMapping = [
            'bar' => 'get91b123d3875702532e36683116824223d37b37377003156fc244abb2a82fec9c',
        ];
    }

    /**
     * Returns the public bar service.
     *
     * @return \Viserio\Component\Container\Tests\Fixture\FactoryClass
     */
    protected function get91b123d3875702532e36683116824223d37b37377003156fc244abb2a82fec9c(): \Viserio\Component\Container\Tests\Fixture\FactoryClass
    {
        $instance = new \Viserio\Component\Container\Tests\Fixture\FactoryClass();

        $a = ($this->privates[\Viserio\Component\Container\Tests\Fixture\FactoryClass::class] ?? $this->gete6b75606779d33c92bdd90effd0a5fe3b4906a4344ab9854f91f135ba070b2f0());

        $instance->returnsParameters($a->create(), $a->create());

        return $instance;
    }

    /**
     * Returns the private Viserio\Component\Container\Tests\Fixture\FactoryClass shared service.
     *
     * @return \Viserio\Component\Container\Tests\Fixture\FactoryClass
     */
    protected function gete6b75606779d33c92bdd90effd0a5fe3b4906a4344ab9854f91f135ba070b2f0(): \Viserio\Component\Container\Tests\Fixture\FactoryClass
    {
        return $this->privates[\Viserio\Component\Container\Tests\Fixture\FactoryClass::class] = new \Viserio\Component\Container\Tests\Fixture\FactoryClass();
    }

    /**
     * {@inheritdoc}
     */
    public function getRemovedIds(): array
    {
        return [
            \Psr\Container\ContainerInterface::class => true,
            \Viserio\Component\Container\Tests\Fixture\FactoryClass::class => true,
            \Viserio\Contract\Container\CompiledContainer::class => true,
            \Viserio\Contract\Container\Factory::class => true,
            \Viserio\Contract\Container\TaggedContainer::class => true,
            'container' => true,
        ];
    }
}
