<?php

declare(strict_types=1);

namespace Viserio\Component\Container\Tests\IntegrationTest\Dumper\Compiled;

/**
 * This class has been auto-generated by Viserio Container Component.
 */
final class PhpDumperContainerTestLazyArgumentProvideGenerator extends \Viserio\Component\Container\AbstractCompiledContainer
{
    /**
     * Create a new Compiled Container instance.
     */
    public function __construct()
    {
        $this->services = $this->privates = [];
        $this->methodMapping = [
            'lazy_context' => 'getdc1c499a0f494602672f377f9bb02214800d1660c4d5bf3fb7e1b79129e0c450',
            'lazy_referenced' => 'getc08d12f61bf4e4314323551ae77da544be2af9b29cf9f10866e4797a464a76d1',
        ];
    }

    /**
     * Returns the public lazy_context shared service.
     *
     * @return \Viserio\Component\Container\Tests\Fixture\File\LazyContext
     */
    protected function getdc1c499a0f494602672f377f9bb02214800d1660c4d5bf3fb7e1b79129e0c450(): \Viserio\Component\Container\Tests\Fixture\File\LazyContext
    {
        return $this->services['lazy_context'] = new \Viserio\Component\Container\Tests\Fixture\File\LazyContext(new \Viserio\Component\Container\RewindableGenerator(function () {
            yield 'k1' => ($this->services['lazy_referenced'] ?? $this->getc08d12f61bf4e4314323551ae77da544be2af9b29cf9f10866e4797a464a76d1());
            yield 'k2' => $this;
        }, 2), new \Viserio\Component\Container\RewindableGenerator(static function () {
            return new \EmptyIterator();
        }, 0));
    }

    /**
     * Returns the public lazy_referenced shared service.
     *
     * @return \stdClass
     */
    protected function getc08d12f61bf4e4314323551ae77da544be2af9b29cf9f10866e4797a464a76d1(): \stdClass
    {
        return $this->services['lazy_referenced'] = new \stdClass();
    }

    /**
     * {@inheritdoc}
     */
    public function getRemovedIds(): array
    {
        return [
            \Psr\Container\ContainerInterface::class => true,
            \Viserio\Contract\Container\Factory::class => true,
            \Viserio\Contract\Container\TaggedContainer::class => true,
            'container' => true,
        ];
    }
}
