<?php

declare(strict_types=1);

namespace Viserio\Component\Container\Tests\IntegrationTest\Dumper\Compiled;

/**
 * This class has been auto-generated by Viserio Container Component.
 */
final class PhpDumperContainerTestDumpRelativeDir extends \Viserio\Component\Container\AbstractCompiledContainer
{
    /**
     * Create a new Compiled Container instance.
     */
    public function __construct()
    {
        $this->services = $this->privates = [];
        $this->parameters = [
            'foo' => ('wiz'.\dirname(__DIR__, 1)),
            'bar' => __DIR__,
            'baz' => (__DIR__.'/PhpDumperTest.php'),
            'buz' => \dirname(__DIR__, 2),
        ];
        $this->methodMapping = [
            \stdClass::class => 'get7505e02fc61bdbec8ef82430242d0041c28f8477d8fc1e70135fd3b6d304a641',
        ];
    }

    /**
     * Returns the public stdClass shared service.
     *
     * @return \stdClass
     */
    protected function get7505e02fc61bdbec8ef82430242d0041c28f8477d8fc1e70135fd3b6d304a641(): \stdClass
    {
        return $this->services[\stdClass::class] = new \stdClass(('wiz'.\dirname(__DIR__, 1)), [
            ('wiz'.\dirname(__DIR__, 1)) => (\dirname(__DIR__, 2).'/'),
        ]);
    }

    /**
     * {@inheritdoc}
     */
    public function getRemovedIds(): array
    {
        return [
            \Psr\Container\ContainerInterface::class => true,
            \Viserio\Contract\Container\Factory::class => true,
            \Viserio\Contract\Container\TaggedContainer::class => true,
            'container' => true,
        ];
    }
}
