<?php

declare(strict_types=1);

/**
 * This file is part of Narrowspark Framework.
 *
 * (c) Daniel Bannert <d.bannert@anolilab.de>
 *
 * This source file is subject to the MIT license that is bundled
 * with this source code in the file LICENSE.
 */

namespace Viserio\Component\Session\Tests\Container\Provider\Compiled;

/**
 * This class has been auto-generated by Viserio Container Component.
 */
if (\class_exists(\ContainerD7fc715f00866a89c5767f6bf10439fb876247e2459e2aa431ace706c6e00935\SessionServiceProviderContainer::class, false)) {
    // no-op
} elseif (! include __DIR__ . '/ContainerD7fc715f00866a89c5767f6bf10439fb876247e2459e2aa431ace706c6e00935/SessionServiceProviderContainer.php') {
    \touch(__DIR__ . '/ContainerD7fc715f00866a89c5767f6bf10439fb876247e2459e2aa431ace706c6e00935.legacy');

    return;
}

if (! \class_exists(SessionServiceProviderContainer::class, false)) {
    \class_alias(\ContainerD7fc715f00866a89c5767f6bf10439fb876247e2459e2aa431ace706c6e00935\SessionServiceProviderContainer::class, SessionServiceProviderContainer::class, false);
}

return new \ContainerD7fc715f00866a89c5767f6bf10439fb876247e2459e2aa431ace706c6e00935\SessionServiceProviderContainer([
    'container.build_hash' => 'D7fc715f00866a89c5767f6bf10439fb876247e2459e2aa431ace706c6e00935',
    'container.build_id' => 'd3ca0edf',
    'container.build_time' => 1565457506,
], __DIR__ . '/ContainerD7fc715f00866a89c5767f6bf10439fb876247e2459e2aa431ace706c6e00935');
