<?php

declare(strict_types=1);

/**
 * This file is part of Narrowspark Framework.
 *
 * (c) Daniel Bannert <d.bannert@anolilab.de>
 *
 * This source file is subject to the MIT license that is bundled
 * with this source code in the file LICENSE.
 */

namespace Viserio\Provider\Twig\Tests\Container\Provider\Compiled;

/**
 * This class has been auto-generated by Viserio Container Component.
 */
if (\class_exists(\Container7f55f385c147561a313d666c99b5c4ad66e9aa4403c0a656b8cc9c32543648a4\TwigServiceProviderContainer::class, false)) {
    // no-op
} elseif (! include __DIR__ . '/Container7f55f385c147561a313d666c99b5c4ad66e9aa4403c0a656b8cc9c32543648a4/TwigServiceProviderContainer.php') {
    \touch(__DIR__ . '/Container7f55f385c147561a313d666c99b5c4ad66e9aa4403c0a656b8cc9c32543648a4.legacy');

    return;
}

if (! \class_exists(TwigServiceProviderContainer::class, false)) {
    \class_alias(\Container7f55f385c147561a313d666c99b5c4ad66e9aa4403c0a656b8cc9c32543648a4\TwigServiceProviderContainer::class, TwigServiceProviderContainer::class, false);
}

return new \Container7f55f385c147561a313d666c99b5c4ad66e9aa4403c0a656b8cc9c32543648a4\TwigServiceProviderContainer([
    'container.build_hash' => '7f55f385c147561a313d666c99b5c4ad66e9aa4403c0a656b8cc9c32543648a4',
    'container.build_id' => '827b75ae',
    'container.build_time' => 1565509025,
], __DIR__ . '/Container7f55f385c147561a313d666c99b5c4ad66e9aa4403c0a656b8cc9c32543648a4');
