<?php

declare(strict_types=1);

namespace Viserio\Component\HttpFoundation\Tests\Provider\Compiled;

/**
 * This class has been auto-generated by Viserio Container Component.
 */
final class WebServerServiceProviderContainer extends \Viserio\Component\Container\AbstractCompiledContainer
{
    /**
     * Create a new Compiled Container instance.
     */
    public function __construct()
    {
        $this->services = $this->privates = [];
        $this->methodMapping = [
            \Symfony\Component\Console\CommandLoader\CommandLoaderInterface::class => 'getce817e8bdc75399a693ba45b876c457a0f7fd422258f7d4eabc553987c2fbd31',
            \Viserio\Component\Console\Application::class => 'get206058a713a7172158e11c9d996f6a067c294ab0356ae6697060f162e057445a',
            \Viserio\Component\HttpFoundation\Console\Command\DownCommand::class => 'getb08920485c647f2c416bb1b88117c7355a1a8abc321f0d3b68784d23e2fff9ac',
            \Viserio\Component\HttpFoundation\Console\Command\UpCommand::class => 'get3b766f0ff9bcb43aa21c2b50b6b6ef2b267a5d89a05616df62cc4c9d184b9730',
            'console.command.ids' => 'getdbce155f9c0e95dbd4bfbfaadab27eb79915789fa80c6c65068ccf60c9ef9e18',
        ];
        $this->aliases = [
            \Symfony\Component\Console\Application::class => \Viserio\Component\Console\Application::class,
            'cerebro' => \Viserio\Component\Console\Application::class,
            'console' => \Viserio\Component\Console\Application::class,
        ];
    }

    /**
     * Returns the public Symfony\Component\Console\CommandLoader\CommandLoaderInterface shared service.
     *
     * @return \Viserio\Component\Console\CommandLoader\IteratorCommandLoader
     */
    protected function getce817e8bdc75399a693ba45b876c457a0f7fd422258f7d4eabc553987c2fbd31(): \Viserio\Component\Console\CommandLoader\IteratorCommandLoader
    {
        return $this->services[\Symfony\Component\Console\CommandLoader\CommandLoaderInterface::class] = new \Viserio\Component\Console\CommandLoader\IteratorCommandLoader(new \Viserio\Component\Container\RewindableGenerator(function () {
            yield 'app:down' => ($this->services[\Viserio\Component\HttpFoundation\Console\Command\DownCommand::class] ?? $this->getb08920485c647f2c416bb1b88117c7355a1a8abc321f0d3b68784d23e2fff9ac());
            yield 'app:up' => ($this->services[\Viserio\Component\HttpFoundation\Console\Command\UpCommand::class] ?? $this->get3b766f0ff9bcb43aa21c2b50b6b6ef2b267a5d89a05616df62cc4c9d184b9730());
        }, 2));
    }

    /**
     * Returns the public Viserio\Component\Console\Application shared service.
     *
     * @return \Viserio\Component\Console\Application
     */
    protected function get206058a713a7172158e11c9d996f6a067c294ab0356ae6697060f162e057445a(): \Viserio\Component\Console\Application
    {
        $this->services[\Viserio\Component\Console\Application::class] = $instance = new \Viserio\Component\Console\Application();

        $instance->setContainer($this);
        if ($this->has(\Symfony\Component\Console\CommandLoader\CommandLoaderInterface::class)) {
            $instance->setCommandLoader(($this->services[\Symfony\Component\Console\CommandLoader\CommandLoaderInterface::class] ?? $this->getce817e8bdc75399a693ba45b876c457a0f7fd422258f7d4eabc553987c2fbd31()));
        }

        return $instance;
    }

    /**
     * Returns the public Viserio\Component\HttpFoundation\Console\Command\DownCommand shared service.
     *
     * @return \Viserio\Component\HttpFoundation\Console\Command\DownCommand
     */
    protected function getb08920485c647f2c416bb1b88117c7355a1a8abc321f0d3b68784d23e2fff9ac(): \Viserio\Component\HttpFoundation\Console\Command\DownCommand
    {
        $this->services[\Viserio\Component\HttpFoundation\Console\Command\DownCommand::class] = $instance = new \Viserio\Component\HttpFoundation\Console\Command\DownCommand();

        $instance->setName('app:down');

        return $instance;
    }

    /**
     * Returns the public Viserio\Component\HttpFoundation\Console\Command\UpCommand shared service.
     *
     * @return \Viserio\Component\HttpFoundation\Console\Command\UpCommand
     */
    protected function get3b766f0ff9bcb43aa21c2b50b6b6ef2b267a5d89a05616df62cc4c9d184b9730(): \Viserio\Component\HttpFoundation\Console\Command\UpCommand
    {
        $this->services[\Viserio\Component\HttpFoundation\Console\Command\UpCommand::class] = $instance = new \Viserio\Component\HttpFoundation\Console\Command\UpCommand();

        $instance->setName('app:up');

        return $instance;
    }

    /**
     * Returns the public console.command.ids service.
     *
     * @return array
     */
    protected function getdbce155f9c0e95dbd4bfbfaadab27eb79915789fa80c6c65068ccf60c9ef9e18(): array
    {
        return [];
    }

    /**
     * {@inheritdoc}
     */
    public function getRemovedIds(): array
    {
        return [
            \Psr\Container\ContainerInterface::class => true,
            \Viserio\Contract\Container\Factory::class => true,
            \Viserio\Contract\Container\TaggedContainer::class => true,
            'container' => true,
        ];
    }
}
