<?php

declare(strict_types=1);

/**
 * This file is part of Narrowspark Framework.
 *
 * (c) Daniel Bannert <d.bannert@anolilab.de>
 *
 * This source file is subject to the MIT license that is bundled
 * with this source code in the file LICENSE.
 */

namespace Viserio\Component\Config\Tests\Container\Provider\Compiled;

/**
 * This class has been auto-generated by Viserio Container Component.
 */
final class ConfigServiceProviderContainer extends \Viserio\Component\Container\AbstractCompiledContainer
{
    /**
     * Create a new Compiled Container instance.
     */
    public function __construct()
    {
        $this->services = $this->privates = [];
        $this->parameters = [
            'container.parameter.provided.processor.types' => [
                'base64' => [
                    0 => 'string',
                ],
                'base64_decode' => [
                    0 => 'string',
                ],
                'const' => [
                    0 => 'bool',
                    1 => 'int',
                    2 => 'float',
                    3 => 'string',
                    4 => 'array',
                ],
                'csv' => [
                    0 => 'array',
                ],
                'str_getcsv' => [
                    0 => 'array',
                ],
                'file' => [
                    0 => 'string',
                ],
                'require' => [
                    0 => 'bool',
                    1 => 'int',
                    2 => 'float',
                    3 => 'string',
                    4 => 'array',
                ],
                'json' => [
                    0 => 'array',
                ],
                'json_decode' => [
                    0 => 'array',
                ],
                'bool' => [
                    0 => 'bool',
                ],
                'float' => [
                    0 => 'float',
                ],
                'int' => [
                    0 => 'int',
                ],
                'string' => [
                    0 => 'string',
                ],
                'trim' => [
                    0 => 'string',
                ],
                'url' => [
                    0 => 'array',
                ],
                'query_string' => [
                    0 => 'array',
                ],
            ],
        ];
        $this->methodMapping = [
            \Viserio\Component\Config\Processor\Base64ParameterProcessor::class => 'get48332f0119f4bcadef91f390117cd83697d72b58d51b9d3db89c85557ad52c81',
            \Viserio\Component\Config\Processor\ConstantProcessor::class => 'geta2bb49bd7703f82b0c33ac9675cbdb68f30e026925e049bcf47078a0ea19ac7c',
            \Viserio\Component\Config\Processor\CsvParameterProcessor::class => 'get192a20062d6bd21d6fcabe5c39643f2a3210c2d1bc10afb828d5dc3bfce7d974',
            \Viserio\Component\Config\Processor\FileParameterProcessor::class => 'getf6fd823f21685121832d5208fbcc6a80e651079220503b1413947f8ab35113f4',
            \Viserio\Component\Config\Processor\JsonParameterProcessor::class => 'geteaf50ab719861def911dcfe84bc8f5fbf25fdd349005c84aad44672a7deb52ef',
            \Viserio\Component\Config\Processor\PhpTypeParameterProcessor::class => 'get7a38524000820df21bb13dd2bb81ecc87c644f68fa3456a5495d6790f172d13c',
            \Viserio\Component\Config\Processor\ResolveParameterProcessor::class => 'get2b6d0a6a4eaf32c4625178a2669930b9e212ff1aae8daea6c8a5dd9ce17b6553',
            \Viserio\Component\Config\Processor\UrlParameterProcessor::class => 'get1108952abf1c485dde7866be4176195d4059a8d0edad277d10b5dd3f2ea72382',
            \Viserio\Component\Console\Application::class => 'get206058a713a7172158e11c9d996f6a067c294ab0356ae6697060f162e057445a',
            \Viserio\Contract\Config\Repository::class => 'get3885c3ded72aac03d06e5943735c8ea35ce46c729563fae6265802054ee9adeb',
            \Viserio\Contract\Parser\Loader::class => 'get5f8d0c5e6b975881f4e6c2651a94e4b5aedf48cf788db67a5c5935449c01c28b',
            'container.parameter.processors' => 'get86047e9365daae20dafc971762ab81fee5d3d066aaa510eba312ea659095239b',
        ];
        $this->aliases = [
            \Symfony\Component\Console\Application::class => \Viserio\Component\Console\Application::class,
            \Viserio\Component\Config\Repository::class => \Viserio\Contract\Config\Repository::class,
            'cerebro' => \Viserio\Component\Console\Application::class,
            'config' => \Viserio\Contract\Config\Repository::class,
            'console' => \Viserio\Component\Console\Application::class,
        ];
    }

    /**
     * Returns the public Viserio\Component\Config\Processor\Base64ParameterProcessor shared service.
     *
     * @return \Viserio\Component\Config\Processor\Base64ParameterProcessor
     */
    protected function get48332f0119f4bcadef91f390117cd83697d72b58d51b9d3db89c85557ad52c81(): \Viserio\Component\Config\Processor\Base64ParameterProcessor
    {
        return $this->services[\Viserio\Component\Config\Processor\Base64ParameterProcessor::class] = new \Viserio\Component\Config\Processor\Base64ParameterProcessor();
    }

    /**
     * Returns the public Viserio\Component\Config\Processor\ConstantProcessor shared service.
     *
     * @return \Viserio\Component\Config\Processor\ConstantProcessor
     */
    protected function geta2bb49bd7703f82b0c33ac9675cbdb68f30e026925e049bcf47078a0ea19ac7c(): \Viserio\Component\Config\Processor\ConstantProcessor
    {
        return $this->services[\Viserio\Component\Config\Processor\ConstantProcessor::class] = new \Viserio\Component\Config\Processor\ConstantProcessor();
    }

    /**
     * Returns the public Viserio\Component\Config\Processor\CsvParameterProcessor shared service.
     *
     * @return \Viserio\Component\Config\Processor\CsvParameterProcessor
     */
    protected function get192a20062d6bd21d6fcabe5c39643f2a3210c2d1bc10afb828d5dc3bfce7d974(): \Viserio\Component\Config\Processor\CsvParameterProcessor
    {
        return $this->services[\Viserio\Component\Config\Processor\CsvParameterProcessor::class] = new \Viserio\Component\Config\Processor\CsvParameterProcessor();
    }

    /**
     * Returns the public Viserio\Component\Config\Processor\FileParameterProcessor shared service.
     *
     * @return \Viserio\Component\Config\Processor\FileParameterProcessor
     */
    protected function getf6fd823f21685121832d5208fbcc6a80e651079220503b1413947f8ab35113f4(): \Viserio\Component\Config\Processor\FileParameterProcessor
    {
        return $this->services[\Viserio\Component\Config\Processor\FileParameterProcessor::class] = new \Viserio\Component\Config\Processor\FileParameterProcessor();
    }

    /**
     * Returns the public Viserio\Component\Config\Processor\JsonParameterProcessor shared service.
     *
     * @return \Viserio\Component\Config\Processor\JsonParameterProcessor
     */
    protected function geteaf50ab719861def911dcfe84bc8f5fbf25fdd349005c84aad44672a7deb52ef(): \Viserio\Component\Config\Processor\JsonParameterProcessor
    {
        return $this->services[\Viserio\Component\Config\Processor\JsonParameterProcessor::class] = new \Viserio\Component\Config\Processor\JsonParameterProcessor();
    }

    /**
     * Returns the public Viserio\Component\Config\Processor\PhpTypeParameterProcessor shared service.
     *
     * @return \Viserio\Component\Config\Processor\PhpTypeParameterProcessor
     */
    protected function get7a38524000820df21bb13dd2bb81ecc87c644f68fa3456a5495d6790f172d13c(): \Viserio\Component\Config\Processor\PhpTypeParameterProcessor
    {
        return $this->services[\Viserio\Component\Config\Processor\PhpTypeParameterProcessor::class] = new \Viserio\Component\Config\Processor\PhpTypeParameterProcessor();
    }

    /**
     * Returns the public Viserio\Component\Config\Processor\ResolveParameterProcessor shared service.
     *
     * @return \Viserio\Component\Config\Processor\ResolveParameterProcessor
     */
    protected function get2b6d0a6a4eaf32c4625178a2669930b9e212ff1aae8daea6c8a5dd9ce17b6553(): \Viserio\Component\Config\Processor\ResolveParameterProcessor
    {
        $a = ($this->services[\Viserio\Contract\Config\Repository::class] ?? $this->get3885c3ded72aac03d06e5943735c8ea35ce46c729563fae6265802054ee9adeb());

        if (isset($this->services[\Viserio\Component\Config\Processor\ResolveParameterProcessor::class])) {
            return $this->services[\Viserio\Component\Config\Processor\ResolveParameterProcessor::class];
        }

        return $this->services[\Viserio\Component\Config\Processor\ResolveParameterProcessor::class] = new \Viserio\Component\Config\Processor\ResolveParameterProcessor($a->getAll());
    }

    /**
     * Returns the public Viserio\Component\Config\Processor\UrlParameterProcessor shared service.
     *
     * @return \Viserio\Component\Config\Processor\UrlParameterProcessor
     */
    protected function get1108952abf1c485dde7866be4176195d4059a8d0edad277d10b5dd3f2ea72382(): \Viserio\Component\Config\Processor\UrlParameterProcessor
    {
        return $this->services[\Viserio\Component\Config\Processor\UrlParameterProcessor::class] = new \Viserio\Component\Config\Processor\UrlParameterProcessor();
    }

    /**
     * Returns the public Viserio\Component\Console\Application shared service.
     *
     * @return \Viserio\Component\Console\Application
     */
    protected function get206058a713a7172158e11c9d996f6a067c294ab0356ae6697060f162e057445a(): \Viserio\Component\Console\Application
    {
        $this->services[\Viserio\Component\Console\Application::class] = $instance = new \Viserio\Component\Console\Application();

        $instance->setContainer($this);

        return $instance;
    }

    /**
     * Returns the public Viserio\Contract\Config\Repository shared service.
     *
     * @return \Viserio\Component\Config\Repository
     */
    protected function get3885c3ded72aac03d06e5943735c8ea35ce46c729563fae6265802054ee9adeb(): \Viserio\Component\Config\Repository
    {
        $this->services[\Viserio\Contract\Config\Repository::class] = $instance = new \Viserio\Component\Config\Repository();

        $instance->setLoader(new \Viserio\Component\Parser\FileLoader());
        $instance->addParameterProcessor(($this->services[\Viserio\Component\Config\Processor\Base64ParameterProcessor::class] ?? $this->get48332f0119f4bcadef91f390117cd83697d72b58d51b9d3db89c85557ad52c81()));
        $instance->addParameterProcessor(($this->services[\Viserio\Component\Config\Processor\ConstantProcessor::class] ?? $this->geta2bb49bd7703f82b0c33ac9675cbdb68f30e026925e049bcf47078a0ea19ac7c()));
        $instance->addParameterProcessor(($this->services[\Viserio\Component\Config\Processor\CsvParameterProcessor::class] ?? $this->get192a20062d6bd21d6fcabe5c39643f2a3210c2d1bc10afb828d5dc3bfce7d974()));
        $instance->addParameterProcessor(($this->services[\Viserio\Component\Config\Processor\FileParameterProcessor::class] ?? $this->getf6fd823f21685121832d5208fbcc6a80e651079220503b1413947f8ab35113f4()));
        $instance->addParameterProcessor(($this->services[\Viserio\Component\Config\Processor\JsonParameterProcessor::class] ?? $this->geteaf50ab719861def911dcfe84bc8f5fbf25fdd349005c84aad44672a7deb52ef()));
        $instance->addParameterProcessor(($this->services[\Viserio\Component\Config\Processor\PhpTypeParameterProcessor::class] ?? $this->get7a38524000820df21bb13dd2bb81ecc87c644f68fa3456a5495d6790f172d13c()));
        $instance->addParameterProcessor(($this->services[\Viserio\Component\Config\Processor\UrlParameterProcessor::class] ?? $this->get1108952abf1c485dde7866be4176195d4059a8d0edad277d10b5dd3f2ea72382()));
        $instance->addParameterProcessor(($this->services[\Viserio\Component\Config\Processor\ResolveParameterProcessor::class] ?? $this->get2b6d0a6a4eaf32c4625178a2669930b9e212ff1aae8daea6c8a5dd9ce17b6553()));

        return $instance;
    }

    /**
     * Returns the public Viserio\Contract\Parser\Loader service.
     *
     * @return \Viserio\Component\Parser\FileLoader
     */
    protected function get5f8d0c5e6b975881f4e6c2651a94e4b5aedf48cf788db67a5c5935449c01c28b(): \Viserio\Component\Parser\FileLoader
    {
        return new \Viserio\Component\Parser\FileLoader();
    }

    /**
     * Returns the public container.parameter.processors shared service.
     *
     * @return \Viserio\Component\Container\RewindableGenerator
     */
    protected function get86047e9365daae20dafc971762ab81fee5d3d066aaa510eba312ea659095239b(): \Viserio\Component\Container\RewindableGenerator
    {
        return $this->services['container.parameter.processors'] = new \Viserio\Component\Container\RewindableGenerator(static function () {
            yield 0 => new \Viserio\Component\Config\Processor\Base64ParameterProcessor();

            yield 1 => new \Viserio\Component\Config\Processor\ConstantProcessor();

            yield 2 => new \Viserio\Component\Config\Processor\CsvParameterProcessor();

            yield 3 => new \Viserio\Component\Config\Processor\FileParameterProcessor();

            yield 4 => new \Viserio\Component\Config\Processor\JsonParameterProcessor();

            yield 5 => new \Viserio\Component\Config\Processor\PhpTypeParameterProcessor();

            yield 6 => new \Viserio\Component\Config\Processor\UrlParameterProcessor();
        }, 7);
    }

    /**
     * {@inheritdoc}
     */
    public function getRemovedIds(): array
    {
        return [
            \Psr\Container\ContainerInterface::class => true,
            \Viserio\Contract\Container\CompiledContainer::class => true,
            \Viserio\Contract\Container\Factory::class => true,
            \Viserio\Contract\Container\TaggedContainer::class => true,
            'container' => true,
        ];
    }
}
