<?php

declare(strict_types=1);

/**
 * This file is part of Narrowspark Framework.
 *
 * (c) Daniel Bannert <d.bannert@anolilab.de>
 *
 * This source file is subject to the MIT license that is bundled
 * with this source code in the file LICENSE.
 */

namespace Viserio\Component\Parser\Tests\Provider\Compiled;

/**
 * This class has been auto-generated by Viserio Container Component.
 */
final class ConsoleCommandsServiceProviderContainer extends \Viserio\Component\Container\AbstractCompiledContainer
{
    /**
     * {@inheritdoc}
     */
    protected $methodMapping = [
        \Symfony\Component\Console\CommandLoader\CommandLoaderInterface::class => 'getce817e8bdc75399a693ba45b876c457a0f7fd422258f7d4eabc553987c2fbd31',
        \Viserio\Component\Console\Application::class => 'get206058a713a7172158e11c9d996f6a067c294ab0356ae6697060f162e057445a',
        \Viserio\Component\Parser\Command\XliffLintCommand::class => 'get12bbcb862884bf3a8245c2cecd4ede5d1f11762e5f8306e98ae45e5e2bddb82e',
        \Viserio\Component\Parser\Command\YamlLintCommand::class => 'getf9bd0df5eff1d91b2afd62180d37e2ef856b803dfe973a759a1331abad74707e',
        'console.command.ids' => 'getdbce155f9c0e95dbd4bfbfaadab27eb79915789fa80c6c65068ccf60c9ef9e18',
    ];

    /**
     * {@inheritdoc}
     */
    protected $tags = [
        'console.command' => [
            0 => \Viserio\Component\Parser\Command\XliffLintCommand::class,
            1 => \Viserio\Component\Parser\Command\YamlLintCommand::class,
        ],
    ];

    /**
     * {@inheritdoc}
     */
    protected $aliases = [
        \Symfony\Component\Console\Application::class => \Viserio\Component\Console\Application::class,
        'cerebro' => \Viserio\Component\Console\Application::class,
        'console' => \Viserio\Component\Console\Application::class,
    ];

    /**
     * {@inheritdoc}
     */
    public function getRemovedIds(): array
    {
        return [
            \Psr\Container\ContainerInterface::class => true,
            \Viserio\Contract\Container\Factory::class => true,
            \Viserio\Contract\Container\TaggedContainer::class => true,
            'container' => true,
            'service_container' => true,
        ];
    }

    /**
     * @return \Viserio\Component\Console\CommandLoader\IteratorCommandLoader
     */
    protected function getce817e8bdc75399a693ba45b876c457a0f7fd422258f7d4eabc553987c2fbd31(): \Viserio\Component\Console\CommandLoader\IteratorCommandLoader
    {
        return $this->services[\Symfony\Component\Console\CommandLoader\CommandLoaderInterface::class] = new \Viserio\Component\Console\CommandLoader\IteratorCommandLoader(new \Viserio\Component\Container\RewindableGenerator(function () {
            yield 'lint:xliff' => ($this->services[\Viserio\Component\Parser\Command\XliffLintCommand::class] ?? $this->get12bbcb862884bf3a8245c2cecd4ede5d1f11762e5f8306e98ae45e5e2bddb82e());

            yield 'lint:yaml' => ($this->services[\Viserio\Component\Parser\Command\YamlLintCommand::class] ?? $this->getf9bd0df5eff1d91b2afd62180d37e2ef856b803dfe973a759a1331abad74707e());
        }, 2));
    }

    /**
     * @return \Viserio\Component\Console\Application
     */
    protected function get206058a713a7172158e11c9d996f6a067c294ab0356ae6697060f162e057445a(): \Viserio\Component\Console\Application
    {
        $this->services[\Viserio\Component\Console\Application::class] = $instance = new \Viserio\Component\Console\Application();

        $instance->setContainer($this);

        if ($this->has(\Symfony\Component\Console\CommandLoader\CommandLoaderInterface::class)) {
            $instance->setCommandLoader(($this->services[\Symfony\Component\Console\CommandLoader\CommandLoaderInterface::class] ?? $this->getce817e8bdc75399a693ba45b876c457a0f7fd422258f7d4eabc553987c2fbd31()));
        }

        return $instance;
    }

    /**
     * @return \Viserio\Component\Parser\Command\XliffLintCommand
     */
    protected function get12bbcb862884bf3a8245c2cecd4ede5d1f11762e5f8306e98ae45e5e2bddb82e(): \Viserio\Component\Parser\Command\XliffLintCommand
    {
        $this->services[\Viserio\Component\Parser\Command\XliffLintCommand::class] = $instance = new \Viserio\Component\Parser\Command\XliffLintCommand();

        $instance->setName('lint:xliff');

        return $instance;
    }

    /**
     * @return \Viserio\Component\Parser\Command\YamlLintCommand
     */
    protected function getf9bd0df5eff1d91b2afd62180d37e2ef856b803dfe973a759a1331abad74707e(): \Viserio\Component\Parser\Command\YamlLintCommand
    {
        $this->services[\Viserio\Component\Parser\Command\YamlLintCommand::class] = $instance = new \Viserio\Component\Parser\Command\YamlLintCommand();

        $instance->setName('lint:yaml');

        return $instance;
    }

    /**
     * @return array
     */
    protected function getdbce155f9c0e95dbd4bfbfaadab27eb79915789fa80c6c65068ccf60c9ef9e18(): array
    {
        return [];
    }
}
