<?php

declare(strict_types=1);

/**
 * This file is part of Narrowspark Framework.
 *
 * (c) Daniel Bannert <d.bannert@anolilab.de>
 *
 * This source file is subject to the MIT license that is bundled
 * with this source code in the file LICENSE.
 */

namespace Viserio\Component\Events\Tests\Provider\Compiled;

/**
 * This class has been auto-generated by Viserio Container Component.
 */
final class EventsServiceProviderContainer extends \Viserio\Component\Container\AbstractCompiledContainer
{
    /**
     * Create a new Compiled Container instance.
     */
    public function __construct()
    {
        $this->services = $this->privates = [];
        $this->methodMapping = [
            \Viserio\Contract\Events\EventManager::class => 'getd89597e6b0951303b9c81d9663646ce16e63e5d0cf7daeed45f04779b8a60c3b',
        ];
        $this->aliases = [
            \Viserio\Component\Events\EventManager::class => \Viserio\Contract\Events\EventManager::class,
            'events' => \Viserio\Contract\Events\EventManager::class,
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function getRemovedIds(): array
    {
        return [
            \Psr\Container\ContainerInterface::class => true,
            \Viserio\Contract\Container\Factory::class => true,
            \Viserio\Contract\Container\TaggedContainer::class => true,
            'container' => true,
        ];
    }

    /**
     * Returns the public Viserio\Contract\Events\EventManager shared service.
     *
     * @return \Viserio\Component\Events\EventManager
     */
    protected function getd89597e6b0951303b9c81d9663646ce16e63e5d0cf7daeed45f04779b8a60c3b(): \Viserio\Component\Events\EventManager
    {
        return $this->services[\Viserio\Contract\Events\EventManager::class] = new \Viserio\Component\Events\EventManager();
    }
}
