name: 'Coding Standard'

on: [push, pull_request]

jobs:
  php-cs-fixer:
    name: 'PHP-CS-Fixer'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: 7.2
      - name: 'lint php code'
        run: |
          composer global require narrowspark/coding-standard:3.1.0 --no-interaction --prefer-dist --no-progress --profile --no-suggest --optimize-autoloader
          cd $GITHUB_WORKSPACE
          /home/runner/.composer/vendor/bin/php-cs-fixer fix -v --dry-run --stop-on-violation
