name: "PHP Coding Standard"

on:
  push:
    paths:
      - "**.php"
  pull_request:
    paths:
      - "**.php"

jobs:
  php-cs-fixer:
    name: "PHP-CS-Fixer"

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2-beta
      - name: Setup PHP
        uses: shivammathur/setup-php@1.6.0
        with:
          php-version: 7.3
          extensions: mbstring, xml, ctype, iconv, zip, dom, fileinfo
      - run: composer global require narrowspark/automatic-composer-prefetcher:dev-master narrowspark/coding-standard:3.2.0 --no-interaction --no-progress --profile --no-suggest --optimize-autoloader
      - name: "lint php code"
        run: |
          cd $GITHUB_WORKSPACE
          /home/runner/.composer/vendor/bin/php-cs-fixer fix --config=$GITHUB_WORKSPACE/.php_cs -v --dry-run --stop-on-violation
