name: "PHP Coding Standard"

on:
  push:
    paths:
      - "**.php"
  pull_request:
    paths:
      - "**.php"

jobs:
  php-cs-fixer:
    name: "PHP-CS-Fixer"

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Setup PHP
        uses: shivammathur/setup-php@2.1.0
        with:
          php-version: "7.4.2"
          extensions: mbstring, xml, ctype, iconv, zip, dom, fileinfo
          tools: composer, composer-prefetcher, cs2pr

      - name: "Install Narrowspark coding standard"
        run: |
          composer global require narrowspark/coding-standard:3.4.0 --no-interaction --no-progress --profile --no-suggest --optimize-autoloader
          # can be removed if bug with ClassAttributesSeparationFixer is fixed in newer version
          composer global require friendsofphp/php-cs-fixer:2.16.x-dev

      - name: "lint php code"
        run: |
          cd $GITHUB_WORKSPACE
          /home/runner/.composer/vendor/bin/php-cs-fixer fix --config=$GITHUB_WORKSPACE/.php_cs -v --dry-run --format=checkstyle | cs2pr
