name: "PHP Static Analyze"

on:
  push:
    paths:
      - "**.php"
  pull_request:
    paths:
      - "**.php"

jobs:
  narrowspark-static-analysis:
    runs-on: ${{ matrix.operating-system }}

    strategy:
      fail-fast: false
      max-parallel: 20
      matrix:
        operating-system: [ubuntu-latest]
        dependencies: [
          "Bridge/Monolog",
          "Bridge/Phpstan",
          "Bridge/Twig",
          "Component/Bus",
          "Component/Cache",
          "Component/Config",
          "Component/Console",
          "Component/Container",
          "Component/Cookie",
          "Component/Cron",
          "Component/Events",
          "Component/Exception",
          "Component/Filesystem",
          "Component/Finder",
          "Component/Foundation",
          "Component/Http",
          "Component/HttpFactory",
          "Component/HttpFoundation",
          "Component/Log",
          "Component/Mail",
          "Component/Manager",
          "Component/Pagination",
          "Component/Parser",
          "Component/Path",
          "Component/Pipeline",
          "Component/Profiler",
#          "Component/Queue",
          "Component/Routing",
          "Component/Session",
          "Component/Support",
          "Component/Translation",
          "Component/Validation",
          "Component/View",
          "Component/WebServer",
          "Provider/Debug",
          "Provider/Framework",
          "Provider/Twig",
          "Contract"
        ]

    name: "${{ matrix.dependencies }}"
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: "Setup PHP"
        uses: shivammathur/setup-php@2.1.0
        with:
          php-version: "7.4.2"
          extensions: mbstring, xml, ctype, iconv, zip, dom, fileinfo, intl, inotify, pcntl, posix
          tools: composer, composer-prefetcher, cs2pr, pecl

      - name: "Configure Container"
        env:
          NARROWSPARK_EMAIL: ${{ secrets.NARROWSPARK_EMAIL }}
          NARROWSPARK_USERNAME: ${{ secrets.NARROWSPARK_USERNAME }}
        run: |
          echo "::set-env name=COMPOSER_UP::composer update --no-progress --no-suggest --no-interaction --prefer-source --ansi"

          EMAIL=${NARROWSPARK_EMAIL:-"d.bannert@anolilab.de"}
          NAME=${NARROWSPARK_USERNAME:-"prisis"}

          git config --global user.email "${EMAIL}"
          git config --global user.name "${NAME}"

      - name: "Check PHP Version"
        run: php -v

      - name: "Check Composer Version"
        run: composer -V

      - name: "List all php extensions with versions"
        run: php -r 'foreach (get_loaded_extensions() as $extension) echo $extension . " " . phpversion($extension) . PHP_EOL;'

      - name: "Create local composer packages for each patched components and reference them in composer.json when cross-testing components"
        run: php ./build/build-packages.php HEAD^ $(find src/Viserio -mindepth 3 -type f -name composer.json -printf '%h\n' | sort)

      - name: "analyze php code"
        run: |
          cd "${GITHUB_WORKSPACE}/src/Viserio/${{ matrix.dependencies }}"

          echo ::group::Composer install
          $COMPOSER_UP
          echo ::endgroup::

          php -d memory_limit=-1 vendor/bin/phpstan analyse --error-format=checkstyle | cs2pr
